{{- if and .Values.gatewayRegional.enabled .Values.gatewayRegional.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ecp.gatewayRegional.serviceAccountName" . }}
  labels:
    {{- include "ecp.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway-regional
  {{- with .Values.gatewayRegional.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
