// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package kubernetes

// +kubebuilder:object:generate=true
// +kubebuilder:object:root=false

import schemav1 "github.com/eu-sovereign-cloud/ecp/framework/persistence/kubernetes/schema/v1"

// Defines values for VolumeReferenceType.

// BlockStorage defines model for BlockStorage.

// Annotations User-defined key/value pairs that are mutable and can be used to add annotations.
// The number of annotations is eventually limited by the CSP.

// Extensions User-defined key/value pairs that are mutable and can be used to add extensions.
// Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.

// Labels User-defined key/value pairs that are mutable and can be used to
// organize and categorize resources. They can be used to filter resources.
// The number of labels is eventually limited by the CSP.

// Metadata Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.

// Spec References the SKU used for this block.
// If a reference to the source image is used as the base for creating this block storage.

// Status The status of the block storage.

// BlockStorageSpec References the SKU used for this block.
// If a reference to the source image is used as the base for creating this block storage.
type BlockStorageSpec struct {
	// SizeGB Size of the block storage in GB.
	SizeGB int `json:"sizeGB" x-cel-message-0:"spec.sizeGB cannot be decreased" x-cel-rule-0:"self >= oldSelf" x-kubebuilder-validation-maximum:"1000000" x-kubebuilder-validation-minimum:"1"`

	// SkuRef Reference to the SKU of the block storage. The SKU is immutable after creation.
	// If you want to change the SKU, you need to create a new block storage and migrate the data.
	SkuRef schemav1.Reference `json:"skuRef" x-cel-message-0:"spec.skuRef is immutable" x-cel-rule-0:"self == oldSelf"`

	// SourceImageRef Reference to the source image used as the base for creating the block storage.
	SourceImageRef *schemav1.Reference `json:"sourceImageRef,omitempty"`
}

// BlockStorageStatus defines model for BlockStorageStatus.
type BlockStorageStatus struct {
	// AttachedTo Reference to the instance the block storage is attached to.
	AttachedTo *schemav1.Reference        `json:"attachedTo,omitempty"`
	Conditions []schemav1.StatusCondition `json:"conditions" x-kubebuilder-validation-max-items:"32"`

	// SizeGB Size of the block storage in GB.
	SizeGB int                    `json:"sizeGB" x-kubebuilder-validation-maximum:"1000000" x-kubebuilder-validation-minimum:"1"`
	State  schemav1.ResourceState `json:"state,omitempty"`
}

// VolumeReference Represents a connection between a Block Storage and an a user of the block storage.

// DeviceRef Reference to the block storage used to store the volume.

// Type The connection type depends on the type of device and type of block storage.

// VolumeReferenceType The connection type depends on the type of device and type of block storage.
