// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/resources/regional/storage/block-storages/v1/backend/kubernetes (interfaces: BlockStoragePlugin)
//
// Generated by this command:
//
//	mockgen -package kubernetes_test -destination /home/antonisio/Devel/Repos/ecp/resources/regional/storage/block-storages/v1/backend/kubernetes/zz_mock_plugin_test.go github.com/eu-sovereign-cloud/ecp/resources/regional/storage/block-storages/v1/backend/kubernetes BlockStoragePlugin
//

// Package kubernetes_test is a generated GoMock package.
package kubernetes_test

import (
	context "context"
	reflect "reflect"

	v1 "github.com/eu-sovereign-cloud/ecp/resources/regional/storage/block-storages/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockBlockStoragePlugin is a mock of BlockStoragePlugin interface.
type MockBlockStoragePlugin struct {
	ctrl     *gomock.Controller
	recorder *MockBlockStoragePluginMockRecorder
	isgomock struct{}
}

// MockBlockStoragePluginMockRecorder is the mock recorder for MockBlockStoragePlugin.
type MockBlockStoragePluginMockRecorder struct {
	mock *MockBlockStoragePlugin
}

// NewMockBlockStoragePlugin creates a new mock instance.
func NewMockBlockStoragePlugin(ctrl *gomock.Controller) *MockBlockStoragePlugin {
	mock := &MockBlockStoragePlugin{ctrl: ctrl}
	mock.recorder = &MockBlockStoragePluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockStoragePlugin) EXPECT() *MockBlockStoragePluginMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBlockStoragePlugin) Create(ctx context.Context, resource *v1.BlockStorage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBlockStoragePluginMockRecorder) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBlockStoragePlugin)(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockBlockStoragePlugin) Delete(ctx context.Context, resource *v1.BlockStorage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBlockStoragePluginMockRecorder) Delete(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBlockStoragePlugin)(nil).Delete), ctx, resource)
}

// IncreaseSize mocks base method.
func (m *MockBlockStoragePlugin) IncreaseSize(ctx context.Context, resource *v1.BlockStorage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseSize", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncreaseSize indicates an expected call of IncreaseSize.
func (mr *MockBlockStoragePluginMockRecorder) IncreaseSize(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseSize", reflect.TypeOf((*MockBlockStoragePlugin)(nil).IncreaseSize), ctx, resource)
}
