// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/resource/network/v1/public-ip/backend/kubernetes (interfaces: PublicIpPlugin)
//
// Generated by this command:
//
//	mockgen -package kubernetes_test -destination ./zz_mock_plugin_test.go github.com/eu-sovereign-cloud/ecp/resource/network/v1/public-ip/backend/kubernetes PublicIpPlugin
//

// Package kubernetes_test is a generated GoMock package.
package kubernetes_test

import (
	context "context"
	reflect "reflect"

	publicip "github.com/eu-sovereign-cloud/ecp/resource/network/v1/public-ip"
	gomock "go.uber.org/mock/gomock"
)

// MockPublicIpPlugin is a mock of PublicIpPlugin interface.
type MockPublicIpPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockPublicIpPluginMockRecorder
	isgomock struct{}
}

// MockPublicIpPluginMockRecorder is the mock recorder for MockPublicIpPlugin.
type MockPublicIpPluginMockRecorder struct {
	mock *MockPublicIpPlugin
}

// NewMockPublicIpPlugin creates a new mock instance.
func NewMockPublicIpPlugin(ctrl *gomock.Controller) *MockPublicIpPlugin {
	mock := &MockPublicIpPlugin{ctrl: ctrl}
	mock.recorder = &MockPublicIpPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublicIpPlugin) EXPECT() *MockPublicIpPluginMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPublicIpPlugin) Create(ctx context.Context, resource *publicip.PublicIp) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPublicIpPluginMockRecorder) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPublicIpPlugin)(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockPublicIpPlugin) Delete(ctx context.Context, resource *publicip.PublicIp) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPublicIpPluginMockRecorder) Delete(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPublicIpPlugin)(nil).Delete), ctx, resource)
}
