//go:build !ignore_autogenerated

// Copyright (c) 2025 The ECP Authors
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of the ECP project and may be used under the terms of the
// Apache License, Version 2.0. You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

// Code generated by conditioned-gen. DO NOT EDIT.

package v1

import (
	genv1 "github.com/eu-sovereign-cloud/ecp/foundation/persistence/generated/types"
	"github.com/eu-sovereign-cloud/ecp/foundation/persistence/regional/common"
)

// Compile-time assertion that *Workspace satisfies common.Conditioned.
var _ common.Conditioned = (*Workspace)(nil)

// GetStatusConditions returns a pointer to the Status.Conditions slice, or nil
// if the receiver or its Status is nil. The returned pointer may reference a
// nil Conditions slice.
func (x *Workspace) GetStatusConditions() *[]genv1.StatusCondition {
	if x == nil || x.Status == nil {
		return nil
	}

	return &x.Status.Conditions
}

// PushStatusCondition appends condition to Status.Conditions and mirrors its
// State onto Status.State, allocating Status or Conditions if needed.
func (x *Workspace) PushStatusCondition(condition genv1.StatusCondition) {
	if x == nil {
		return
	}

	if x.Status == nil {
		x.Status = &genv1.WorkspaceStatus{}
	}

	if x.Status.Conditions == nil {
		x.Status.Conditions = []genv1.StatusCondition{}
	}

	x.Status.Conditions = append(x.Status.Conditions, condition)
	x.Status.State = condition.State
}

// PopStatusCondition removes the oldest (head) entry from Status.Conditions.
// It is a no-op when the slice is empty or the receiver has no status.
func (x *Workspace) PopStatusCondition() {
	if x == nil || x.Status == nil || len(x.Status.Conditions) == 0 {
		return
	}

	x.Status.Conditions = x.Status.Conditions[1:]
}

// LenStatusConditions returns the length of Status.Conditions slice,
// or zero if the receiver, its Status, or the slice itself is nil.
func (x *Workspace) LenStatusConditions() int {
	if x == nil || x.Status == nil {
		return 0
	}

	return len(x.Status.Conditions)
}
