// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/resource/network/network/v1/backend/kubernetes (interfaces: NetworkPlugin)
//
// Generated by this command:
//
//	mockgen -package kubernetes_test -destination /home/antonisio/Devel/Repos/ecp/resource/network/network/v1/backend/kubernetes/zz_mock_plugin_test.go github.com/eu-sovereign-cloud/ecp/resource/network/network/v1/backend/kubernetes NetworkPlugin
//

// Package kubernetes_test is a generated GoMock package.
package kubernetes_test

import (
	context "context"
	reflect "reflect"

	v1 "github.com/eu-sovereign-cloud/ecp/resource/network/network/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockNetworkPlugin is a mock of NetworkPlugin interface.
type MockNetworkPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkPluginMockRecorder
	isgomock struct{}
}

// MockNetworkPluginMockRecorder is the mock recorder for MockNetworkPlugin.
type MockNetworkPluginMockRecorder struct {
	mock *MockNetworkPlugin
}

// NewMockNetworkPlugin creates a new mock instance.
func NewMockNetworkPlugin(ctrl *gomock.Controller) *MockNetworkPlugin {
	mock := &MockNetworkPlugin{ctrl: ctrl}
	mock.recorder = &MockNetworkPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkPlugin) EXPECT() *MockNetworkPluginMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNetworkPlugin) Create(ctx context.Context, resource *v1.Network) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNetworkPluginMockRecorder) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNetworkPlugin)(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockNetworkPlugin) Delete(ctx context.Context, resource *v1.Network) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNetworkPluginMockRecorder) Delete(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNetworkPlugin)(nil).Delete), ctx, resource)
}
