// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/resource/network/v1/security-group-rule/backend/kubernetes (interfaces: SecurityGroupRulePlugin)
//
// Generated by this command:
//
//	mockgen -package kubernetes_test -destination ./zz_mock_plugin_test.go github.com/eu-sovereign-cloud/ecp/resource/network/v1/security-group-rule/backend/kubernetes SecurityGroupRulePlugin
//

// Package kubernetes_test is a generated GoMock package.
package kubernetes_test

import (
	context "context"
	reflect "reflect"

	securitygrouprule "github.com/eu-sovereign-cloud/ecp/resource/network/v1/security-group-rule"
	gomock "go.uber.org/mock/gomock"
)

// MockSecurityGroupRulePlugin is a mock of SecurityGroupRulePlugin interface.
type MockSecurityGroupRulePlugin struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityGroupRulePluginMockRecorder
	isgomock struct{}
}

// MockSecurityGroupRulePluginMockRecorder is the mock recorder for MockSecurityGroupRulePlugin.
type MockSecurityGroupRulePluginMockRecorder struct {
	mock *MockSecurityGroupRulePlugin
}

// NewMockSecurityGroupRulePlugin creates a new mock instance.
func NewMockSecurityGroupRulePlugin(ctrl *gomock.Controller) *MockSecurityGroupRulePlugin {
	mock := &MockSecurityGroupRulePlugin{ctrl: ctrl}
	mock.recorder = &MockSecurityGroupRulePluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityGroupRulePlugin) EXPECT() *MockSecurityGroupRulePluginMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSecurityGroupRulePlugin) Create(ctx context.Context, resource *securitygrouprule.SecurityGroupRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSecurityGroupRulePluginMockRecorder) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSecurityGroupRulePlugin)(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockSecurityGroupRulePlugin) Delete(ctx context.Context, resource *securitygrouprule.SecurityGroupRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSecurityGroupRulePluginMockRecorder) Delete(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSecurityGroupRulePlugin)(nil).Delete), ctx, resource)
}
