// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/resource/compute/v1/instance/backend/kubernetes (interfaces: InstancePlugin)
//
// Generated by this command:
//
//	mockgen -package kubernetes_test -destination ./zz_mock_plugin_test.go github.com/eu-sovereign-cloud/ecp/resource/compute/v1/instance/backend/kubernetes InstancePlugin
//

// Package kubernetes_test is a generated GoMock package.
package kubernetes_test

import (
	context "context"
	reflect "reflect"

	instance "github.com/eu-sovereign-cloud/ecp/resource/compute/v1/instance"
	gomock "go.uber.org/mock/gomock"
)

// MockInstancePlugin is a mock of InstancePlugin interface.
type MockInstancePlugin struct {
	ctrl     *gomock.Controller
	recorder *MockInstancePluginMockRecorder
	isgomock struct{}
}

// MockInstancePluginMockRecorder is the mock recorder for MockInstancePlugin.
type MockInstancePluginMockRecorder struct {
	mock *MockInstancePlugin
}

// NewMockInstancePlugin creates a new mock instance.
func NewMockInstancePlugin(ctrl *gomock.Controller) *MockInstancePlugin {
	mock := &MockInstancePlugin{ctrl: ctrl}
	mock.recorder = &MockInstancePluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstancePlugin) EXPECT() *MockInstancePluginMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInstancePlugin) Create(ctx context.Context, resource *instance.Instance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockInstancePluginMockRecorder) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInstancePlugin)(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockInstancePlugin) Delete(ctx context.Context, resource *instance.Instance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInstancePluginMockRecorder) Delete(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInstancePlugin)(nil).Delete), ctx, resource)
}

// PowerOff mocks base method.
func (m *MockInstancePlugin) PowerOff(ctx context.Context, resource *instance.Instance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PowerOff", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// PowerOff indicates an expected call of PowerOff.
func (mr *MockInstancePluginMockRecorder) PowerOff(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PowerOff", reflect.TypeOf((*MockInstancePlugin)(nil).PowerOff), ctx, resource)
}

// PowerOn mocks base method.
func (m *MockInstancePlugin) PowerOn(ctx context.Context, resource *instance.Instance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PowerOn", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// PowerOn indicates an expected call of PowerOn.
func (mr *MockInstancePluginMockRecorder) PowerOn(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PowerOn", reflect.TypeOf((*MockInstancePlugin)(nil).PowerOn), ctx, resource)
}

// Update mocks base method.
func (m *MockInstancePlugin) Update(ctx context.Context, resource *instance.Instance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInstancePluginMockRecorder) Update(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInstancePlugin)(nil).Update), ctx, resource)
}
