// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/resource/authorization/v1/role/backend/kubernetes (interfaces: RolePlugin)
//
// Generated by this command:
//
//	mockgen -package kubernetes_test -destination ./zz_mock_plugin_test.go github.com/eu-sovereign-cloud/ecp/resource/authorization/v1/role/backend/kubernetes RolePlugin
//

// Package kubernetes_test is a generated GoMock package.
package kubernetes_test

import (
	context "context"
	reflect "reflect"

	v1 "github.com/eu-sovereign-cloud/ecp/resource/authorization/v1/role"
	gomock "go.uber.org/mock/gomock"
)

// MockRolePlugin is a mock of RolePlugin interface.
type MockRolePlugin struct {
	ctrl     *gomock.Controller
	recorder *MockRolePluginMockRecorder
	isgomock struct{}
}

// MockRolePluginMockRecorder is the mock recorder for MockRolePlugin.
type MockRolePluginMockRecorder struct {
	mock *MockRolePlugin
}

// NewMockRolePlugin creates a new mock instance.
func NewMockRolePlugin(ctrl *gomock.Controller) *MockRolePlugin {
	mock := &MockRolePlugin{ctrl: ctrl}
	mock.recorder = &MockRolePluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRolePlugin) EXPECT() *MockRolePluginMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRolePlugin) Create(ctx context.Context, resource *v1.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRolePluginMockRecorder) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRolePlugin)(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockRolePlugin) Delete(ctx context.Context, resource *v1.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRolePluginMockRecorder) Delete(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRolePlugin)(nil).Delete), ctx, resource)
}
