// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package kubernetes

// +kubebuilder:object:generate=true
// +kubebuilder:object:root=false

import genv1 "github.com/eu-sovereign-cloud/ecp/framework/persistence/kubernetes/schema/v1"

// InternetGateway defines model for InternetGateway.

// Annotations User-defined key/value pairs that are mutable and can be used to add annotations.
// The number of annotations is eventually limited by the CSP.

// Extensions User-defined key/value pairs that are mutable and can be used to add extensions.
// Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.

// Labels User-defined key/value pairs that are mutable and can be used to
// organize and categorize resources. They can be used to filter resources.
// The number of labels is eventually limited by the CSP.

// Metadata Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.

// Spec The internet gateway will use the reserved IP addres.
// the subnet CIDR block to provide internet access to the subnet.

// Status Current status of the resource

// InternetGatewaySpec The internet gateway will use the reserved IP addres.
// the subnet CIDR block to provide internet access to the subnet.
type InternetGatewaySpec struct {
	// EgressOnly If set to true, the internet gateway will only allow outgoing traffic
	// and will not allow incoming traffic. This is useful for public subnets
	// that should not be accessible from the internet.
	EgressOnly bool `json:"egressOnly,omitempty" x-kubebuilder-default:"false"`
}

// InternetGatewayStatus Current status of the resource
type InternetGatewayStatus = genv1.Status
