// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package kubernetes

// +kubebuilder:object:generate=true
// +kubebuilder:object:root=false

import schemav1 "github.com/eu-sovereign-cloud/ecp/framework/backend/kubernetes/schema/v1"

// SecurityGroup defines model for SecurityGroup.

// Annotations User-defined key/value pairs that are mutable and can be used to add annotations.
// The number of annotations is eventually limited by the CSP.

// Extensions User-defined key/value pairs that are mutable and can be used to add extensions.
// Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.

// Labels User-defined key/value pairs that are mutable and can be used to
// organize and categorize resources. They can be used to filter resources.
// The number of labels is eventually limited by the CSP.

// Metadata Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.

// Spec Specification of the security group

// Status Status of the security group, including the status of its rules.
// The status is read-only and reflects the current state of the security group.

// SecurityGroupSpec Specification of the security group
type SecurityGroupSpec struct {
	// RuleRefs References to shared SecurityGroupRule resources.
	// These rules are applied in addition to the inline rules.
	// +kubebuilder:validation:MaxItems=500
	RuleRefs []schemav1.Reference `json:"ruleRefs,omitempty" x-kubebuilder-validation-max-items:"500"`

	// Rules Network access rules defining communication between security groups and external networks.
	//
	// Rule Evaluation:
	// - Default behavior is to deny all traffic not explicitly allowed
	// - Rules provide granular control over allowed traffic types, sources, and destinations
	// +kubebuilder:validation:MaxItems=500
	Rules []SecurityGroupRuleSpec `json:"rules,omitempty" x-kubebuilder-validation-max-items:"500"`
}

// SecurityGroupStatus defines model for SecurityGroupStatus.
type SecurityGroupStatus struct {
	// +kubebuilder:validation:MaxItems=32
	Conditions []schemav1.StatusCondition `json:"conditions" x-kubebuilder-validation-max-items:"32"`
	// +kubebuilder:validation:MaxItems=500
	Rules      []SecurityGroupRuleStatus  `json:"rules,omitempty" x-kubebuilder-validation-max-items:"500"`
	State      schemav1.ResourceState     `json:"state,omitempty"`
}

const (
	SecurityGroupRuleDirectionEgress  SecurityGroupRuleSpecDirection = "egress"
	SecurityGroupRuleDirectionIngress SecurityGroupRuleSpecDirection = "ingress"
)

const (
	SecurityGroupRuleProtocolICMP   SecurityGroupRuleSpecProtocol = "icmp"
	SecurityGroupRuleProtocolTCP    SecurityGroupRuleSpecProtocol = "tcp"
	SecurityGroupRuleProtocolTCPUDP SecurityGroupRuleSpecProtocol = "tcp+udp"
	SecurityGroupRuleProtocolUDP    SecurityGroupRuleSpecProtocol = "udp"
)

type IcmpConfig struct {
	// +kubebuilder:validation:Maximum=5
	// +kubebuilder:validation:Minimum=0
	Code int `json:"code" x-kubebuilder-validation-maximum:"5" x-kubebuilder-validation-minimum:"0"`

	// +kubebuilder:validation:Maximum=8
	// +kubebuilder:validation:Minimum=0
	Type int `json:"type" x-kubebuilder-validation-maximum:"8" x-kubebuilder-validation-minimum:"0"`
}

type Port = int

type Ports struct {
	From Port   `json:"from,omitempty"`
	// +kubebuilder:validation:MaxItems=100
	// +kubebuilder:validation:items:Maximum=65535
	// +kubebuilder:validation:items:Minimum=1
	List []Port `json:"list,omitempty" x-kubebuilder-validation-items-maximum:"65535" x-kubebuilder-validation-items-minimum:"1" x-kubebuilder-validation-max-items:"100"`
	To   Port   `json:"to,omitempty"`
}

type SecurityGroupRuleSpec struct {
	Annotations schemav1.Annotations `json:"annotations,omitempty"`

	// +kubebuilder:validation:Type=string
	// +kubebuilder:validation:Enum=ingress;egress
	// +kubebuilder:validation:MaxLength=7
	Direction SecurityGroupRuleSpecDirection `json:"direction" x-kubebuilder-validation-enum:"ingress;egress" x-kubebuilder-validation-max-length:"7"`

	Icmp *IcmpConfig `json:"icmp,omitempty"`

	Ports *Ports `json:"ports,omitempty"`

	// +kubebuilder:validation:Type=string
	// +kubebuilder:validation:Enum=tcp;udp;tcp+udp;icmp
	// +kubebuilder:validation:MaxLength=7
	Protocol SecurityGroupRuleSpecProtocol `json:"protocol,omitempty" x-kubebuilder-validation-enum:"tcp;udp;tcp+udp;icmp" x-kubebuilder-validation-max-length:"7"`

	// +kubebuilder:validation:MaxItems=32
	SourceRef []schemav1.Reference `json:"sourceRef,omitempty" x-kubebuilder-validation-max-items:"32"`
	Version   schemav1.IPVersion   `json:"version,omitempty"`
}

type SecurityGroupRuleSpecDirection string

type SecurityGroupRuleSpecProtocol string

type SecurityGroupRuleStatus = schemav1.Status
