// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/resource/network/v1/security-group/backend/kubernetes (interfaces: SecurityGroupPlugin)
//
// Generated by this command:
//
//	mockgen -package kubernetes_test -destination ./zz_mock_plugin_test.go github.com/eu-sovereign-cloud/ecp/resource/network/v1/security-group/backend/kubernetes SecurityGroupPlugin
//

// Package kubernetes_test is a generated GoMock package.
package kubernetes_test

import (
	context "context"
	reflect "reflect"

	securitygroup "github.com/eu-sovereign-cloud/ecp/resource/network/v1/security-group"
	gomock "go.uber.org/mock/gomock"
)

// MockSecurityGroupPlugin is a mock of SecurityGroupPlugin interface.
type MockSecurityGroupPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityGroupPluginMockRecorder
	isgomock struct{}
}

// MockSecurityGroupPluginMockRecorder is the mock recorder for MockSecurityGroupPlugin.
type MockSecurityGroupPluginMockRecorder struct {
	mock *MockSecurityGroupPlugin
}

// NewMockSecurityGroupPlugin creates a new mock instance.
func NewMockSecurityGroupPlugin(ctrl *gomock.Controller) *MockSecurityGroupPlugin {
	mock := &MockSecurityGroupPlugin{ctrl: ctrl}
	mock.recorder = &MockSecurityGroupPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityGroupPlugin) EXPECT() *MockSecurityGroupPluginMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSecurityGroupPlugin) Create(ctx context.Context, resource *securitygroup.SecurityGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSecurityGroupPluginMockRecorder) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSecurityGroupPlugin)(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockSecurityGroupPlugin) Delete(ctx context.Context, resource *securitygroup.SecurityGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSecurityGroupPluginMockRecorder) Delete(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSecurityGroupPlugin)(nil).Delete), ctx, resource)
}

// Update mocks base method.
func (m *MockSecurityGroupPlugin) Update(ctx context.Context, resource *securitygroup.SecurityGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSecurityGroupPluginMockRecorder) Update(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSecurityGroupPlugin)(nil).Update), ctx, resource)
}
