// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/foundation/gateway/pkg/port (interfaces: Repo)
//
// Generated by this command:
//
//	mockgen -package controller -destination=zz_mock_blockstorage_repo_test.go github.com/eu-sovereign-cloud/ecp/foundation/gateway/pkg/port Repo
//

// Package controller is a generated GoMock package.
package controller

import (
	context "context"
	reflect "reflect"

	model "github.com/eu-sovereign-cloud/ecp/foundation/gateway/pkg/model"
	port "github.com/eu-sovereign-cloud/ecp/foundation/gateway/pkg/port"
	gomock "go.uber.org/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo[T port.IdentifiableResource] struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder[T]
	isgomock struct{}
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder[T port.IdentifiableResource] struct {
	mock *MockRepo[T]
}

// NewMockRepo creates a new mock instance.
func NewMockRepo[T port.IdentifiableResource](ctrl *gomock.Controller) *MockRepo[T] {
	mock := &MockRepo[T]{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo[T]) EXPECT() *MockRepoMockRecorder[T] {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockRepo[T]) Create(ctx context.Context, m T) (*T, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepoMockRecorder[T]) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepo[T])(nil).Create), ctx, m)
}

// Delete mocks base method.
func (m_2 *MockRepo[T]) Delete(ctx context.Context, m T) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Delete", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepoMockRecorder[T]) Delete(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepo[T])(nil).Delete), ctx, m)
}

// List mocks base method.
func (m *MockRepo[T]) List(ctx context.Context, params model.ListParams, list *[]T) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params, list)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepoMockRecorder[T]) List(ctx, params, list any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepo[T])(nil).List), ctx, params, list)
}

// Load mocks base method.
func (m_2 *MockRepo[T]) Load(ctx context.Context, m *T) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Load", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockRepoMockRecorder[T]) Load(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockRepo[T])(nil).Load), ctx, m)
}

// Update mocks base method.
func (m_2 *MockRepo[T]) Update(ctx context.Context, m T) (*T, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ctx, m)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRepoMockRecorder[T]) Update(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepo[T])(nil).Update), ctx, m)
}

// Watch mocks base method.
func (m_2 *MockRepo[T]) Watch(ctx context.Context, m chan<- T) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Watch", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MockRepoMockRecorder[T]) Watch(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockRepo[T])(nil).Watch), ctx, m)
}
