// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/foundation/delegator/pkg/port (interfaces: PluginHandler)
//
// Generated by this command:
//
//	mockgen -package controller -destination=zz_mock_plugin_handler_test.go github.com/eu-sovereign-cloud/ecp/foundation/delegator/pkg/port PluginHandler
//

// Package controller is a generated GoMock package.
package controller

import (
	context "context"
	reflect "reflect"

	port "github.com/eu-sovereign-cloud/ecp/foundation/gateway/pkg/port"
	gomock "go.uber.org/mock/gomock"
)

// MockPluginHandler is a mock of PluginHandler interface.
type MockPluginHandler[T port.IdentifiableResource] struct {
	ctrl     *gomock.Controller
	recorder *MockPluginHandlerMockRecorder[T]
	isgomock struct{}
}

// MockPluginHandlerMockRecorder is the mock recorder for MockPluginHandler.
type MockPluginHandlerMockRecorder[T port.IdentifiableResource] struct {
	mock *MockPluginHandler[T]
}

// NewMockPluginHandler creates a new mock instance.
func NewMockPluginHandler[T port.IdentifiableResource](ctrl *gomock.Controller) *MockPluginHandler[T] {
	mock := &MockPluginHandler[T]{ctrl: ctrl}
	mock.recorder = &MockPluginHandlerMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPluginHandler[T]) EXPECT() *MockPluginHandlerMockRecorder[T] {
	return m.recorder
}

// HandleAdmission mocks base method.
func (m *MockPluginHandler[T]) HandleAdmission(ctx context.Context, resource T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleAdmission", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleAdmission indicates an expected call of HandleAdmission.
func (mr *MockPluginHandlerMockRecorder[T]) HandleAdmission(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleAdmission", reflect.TypeOf((*MockPluginHandler[T])(nil).HandleAdmission), ctx, resource)
}

// HandleReconcile mocks base method.
func (m *MockPluginHandler[T]) HandleReconcile(ctx context.Context, resource T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleReconcile", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleReconcile indicates an expected call of HandleReconcile.
func (mr *MockPluginHandlerMockRecorder[T]) HandleReconcile(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleReconcile", reflect.TypeOf((*MockPluginHandler[T])(nil).HandleReconcile), ctx, resource)
}
