// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/foundation/delegator/pkg/port (interfaces: ResourceHandler)
//
// Generated by this command:
//
//	mockgen -package controller -destination=zz_mock_resource_handler_test.go github.com/eu-sovereign-cloud/ecp/foundation/delegator/pkg/port ResourceHandler
//

// Package controller is a generated GoMock package.
package controller

import (
	context "context"
	reflect "reflect"

	port "github.com/eu-sovereign-cloud/ecp/foundation/gateway/pkg/port"
	gomock "go.uber.org/mock/gomock"
)

// MockResourceHandler is a mock of ResourceHandler interface.
type MockResourceHandler[T port.IdentifiableResource] struct {
	ctrl     *gomock.Controller
	recorder *MockResourceHandlerMockRecorder[T]
	isgomock struct{}
}

// MockResourceHandlerMockRecorder is the mock recorder for MockResourceHandler.
type MockResourceHandlerMockRecorder[T port.IdentifiableResource] struct {
	mock *MockResourceHandler[T]
}

// NewMockResourceHandler creates a new mock instance.
func NewMockResourceHandler[T port.IdentifiableResource](ctrl *gomock.Controller) *MockResourceHandler[T] {
	mock := &MockResourceHandler[T]{ctrl: ctrl}
	mock.recorder = &MockResourceHandlerMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceHandler[T]) EXPECT() *MockResourceHandlerMockRecorder[T] {
	return m.recorder
}

// HandleAdmission mocks base method.
func (m *MockResourceHandler[T]) HandleAdmission(ctx context.Context, resource T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleAdmission", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleAdmission indicates an expected call of HandleAdmission.
func (mr *MockResourceHandlerMockRecorder[T]) HandleAdmission(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleAdmission", reflect.TypeOf((*MockResourceHandler[T])(nil).HandleAdmission), ctx, resource)
}

// HandleReconcile mocks base method.
func (m *MockResourceHandler[T]) HandleReconcile(ctx context.Context, resource T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleReconcile", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleReconcile indicates an expected call of HandleReconcile.
func (mr *MockResourceHandlerMockRecorder[T]) HandleReconcile(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleReconcile", reflect.TypeOf((*MockResourceHandler[T])(nil).HandleReconcile), ctx, resource)
}
