// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/resource/network/v1/internet-gateway/backend/kubernetes (interfaces: InternetGatewayPlugin)
//
// Generated by this command:
//
//	mockgen -package kubernetes_test -destination ./zz_mock_plugin_test.go github.com/eu-sovereign-cloud/ecp/resource/network/v1/internet-gateway/backend/kubernetes InternetGatewayPlugin
//

// Package kubernetes_test is a generated GoMock package.
package kubernetes_test

import (
	context "context"
	reflect "reflect"

	internetgateway "github.com/eu-sovereign-cloud/ecp/resource/network/v1/internet-gateway"
	gomock "go.uber.org/mock/gomock"
)

// MockInternetGatewayPlugin is a mock of InternetGatewayPlugin interface.
type MockInternetGatewayPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockInternetGatewayPluginMockRecorder
	isgomock struct{}
}

// MockInternetGatewayPluginMockRecorder is the mock recorder for MockInternetGatewayPlugin.
type MockInternetGatewayPluginMockRecorder struct {
	mock *MockInternetGatewayPlugin
}

// NewMockInternetGatewayPlugin creates a new mock instance.
func NewMockInternetGatewayPlugin(ctrl *gomock.Controller) *MockInternetGatewayPlugin {
	mock := &MockInternetGatewayPlugin{ctrl: ctrl}
	mock.recorder = &MockInternetGatewayPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInternetGatewayPlugin) EXPECT() *MockInternetGatewayPluginMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInternetGatewayPlugin) Create(ctx context.Context, resource *internetgateway.InternetGateway) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockInternetGatewayPluginMockRecorder) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInternetGatewayPlugin)(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockInternetGatewayPlugin) Delete(ctx context.Context, resource *internetgateway.InternetGateway) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInternetGatewayPluginMockRecorder) Delete(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInternetGatewayPlugin)(nil).Delete), ctx, resource)
}

// Update mocks base method.
func (m *MockInternetGatewayPlugin) Update(ctx context.Context, resource *internetgateway.InternetGateway) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInternetGatewayPluginMockRecorder) Update(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInternetGatewayPlugin)(nil).Update), ctx, resource)
}
