// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package kubernetes

// +kubebuilder:object:generate=true
// +kubebuilder:object:root=false

import schemav1 "github.com/eu-sovereign-cloud/ecp/framework/persistence/kubernetes/schema/v1"

// Defines values for IPVersion.

// IPVersion IP version of the address

// Network defines model for Network.

// Annotations User-defined key/value pairs that are mutable and can be used to add annotations.
// The number of annotations is eventually limited by the CSP.

// Extensions User-defined key/value pairs that are mutable and can be used to add extensions.
// Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.

// Labels User-defined key/value pairs that are mutable and can be used to
// organize and categorize resources. They can be used to filter resources.
// The number of labels is eventually limited by the CSP.

// Metadata Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.

// Spec A Network represents a virtual network that can be used to isolate resources.
// Key network concepts:
//
// * Defines a range of IP addresses for compute resources (e.g. instances)
// * Enables network segmentation and isolation
// * Provides common performance configuration across the network using a SKU
//
// The `cidr` is the base CIDR block for the network. Additional CIDR blocks can be
// added to the network using the `additionalCidrs` field. The `additionalCidrs` can
// be changed after the network is created in case they are not used. The main CIDR
// block cannot be changed after the network is created. All cidrs must be non-overlapping.
// The cidrs have to be part of the RFC 1918 address space in case of IPv4 and or RFC 4193.
//
// In case the system should automatically assign IP addresses to the network cidrs
// only the network prefix is required. E.g. to request a /16 IPv4 CIDR block the
// CIDR block would be `0.0.0.0/16` and for a /56 IPv6 CIDR block the CIDR block would
// be `::/56`. Most CSP will not allow to use a different IPv6 prefix length than /56.

// Status The status of the network. The status is read-only and will be set by the
// system. The status contains information about the current state of the network
// and its CIDR blocks. It will report the status of the CIDR blocks and the network
// as a whole including automatically assigned IP networks.

// NetworkSpec A Network represents a virtual network that can be used to isolate resources.
// Key network concepts:
//
// * Defines a range of IP addresses for compute resources (e.g. instances)
// * Enables network segmentation and isolation
// * Provides common performance configuration across the network using a SKU
//
// The `cidr` is the base CIDR block for the network. Additional CIDR blocks can be
// added to the network using the `additionalCidrs` field. The `additionalCidrs` can
// be changed after the network is created in case they are not used. The main CIDR
// block cannot be changed after the network is created. All cidrs must be non-overlapping.
// The cidrs have to be part of the RFC 1918 address space in case of IPv4 and or RFC 4193.
//
// In case the system should automatically assign IP addresses to the network cidrs
// only the network prefix is required. E.g. to request a /16 IPv4 CIDR block the
// CIDR block would be `0.0.0.0/16` and for a /56 IPv6 CIDR block the CIDR block would
// be `::/56`. Most CSP will not allow to use a different IPv6 prefix length than /56.
type NetworkSpec struct {
	AdditionalCidrs []schemav1.Cidr `json:"additionalCidrs,omitempty" x-kubebuilder-validation-max-items:"32"`

	// Cidr Combined IPv4 and IPv6 CIDR block for a subnet. Depending on the network
	// configuration, either the IPv4 or IPv6 range can be omitted. So the following
	// combinations are possible:
	//
	// * IPv4 only
	// * IPv6 only
	// * IPv4 and IPv6 (Dual Stack)
	Cidr schemav1.Cidr `json:"cidr"`

	// RouteTableRef Reference to the route table used by default for all Subnets.
	RouteTableRef schemav1.Reference `json:"routeTableRef"`

	// SkuRef Reference to the SKU used by default for all NIC in this Network.
	// Can be overridden by the NIC. The SKU is immutable after the network is created.
	// To change the SKU, the network must be deleted and recreated with the new SKU reference.
	SkuRef schemav1.Reference `json:"skuRef" x-cel-message-0:"spec.skuRef is immutable" x-cel-rule-0:"self == oldSelf"`
}

// NetworkStatus defines model for NetworkStatus.
type NetworkStatus struct {
	AdditionalCidrs []schemav1.Cidr `json:"additionalCidrs,omitempty" x-kubebuilder-validation-max-items:"32"`

	// Cidr Combined IPv4 and IPv6 CIDR block for a subnet. Depending on the network
	// configuration, either the IPv4 or IPv6 range can be omitted. So the following
	// combinations are possible:
	//
	// * IPv4 only
	// * IPv6 only
	// * IPv4 and IPv6 (Dual Stack)
	Cidr       schemav1.Cidr              `json:"cidr"`
	Conditions []schemav1.StatusCondition `json:"conditions" x-kubebuilder-validation-max-items:"32"`

	// RouteTableRef Reference to the route table used by default for all Subnets.
	RouteTableRef *schemav1.Reference    `json:"routeTableRef,omitempty"`
	State         schemav1.ResourceState `json:"state,omitempty"`
}

// Cidr Combined IPv4 and IPv6 CIDR block for a subnet. Depending on the network
// configuration, either the IPv4 or IPv6 range can be omitted. So the following
// combinations are possible:
//
// * IPv4 only
// * IPv6 only
// * IPv4 and IPv6 (Dual Stack)

// Ipv4 IPv4 CIDR block for the subnet.

// Ipv6 IPv6 CIDR block for the subnet.
