package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

const (
	marker             = "+ecp:conditioned"
	statusTypesPkgPath = "github.com/eu-sovereign-cloud/ecp/foundation/persistence/generated/types"
)

type targetType struct {
	Name          string
	StatusTypeRef string
}

type fileData struct {
	Header      string
	PackageName string
	Targets     []targetType
}

const fileTemplate = `//go:build !ignore_autogenerated

{{.Header}}// Code generated by conditioned-gen. DO NOT EDIT.

package {{.PackageName}}

import (
	"github.com/eu-sovereign-cloud/ecp/foundation/persistence/generated/types"
	"github.com/eu-sovereign-cloud/ecp/foundation/persistence/regional/common"
)
{{range .Targets}}
// Compile-time assertion that *{{.Name}} satisfies common.Conditioned.
var _ common.Conditioned = (*{{.Name}})(nil)

// GetConditions returns a pointer to the Status.Conditions slice, or nil
// if the receiver or its Status is nil. The returned pointer may reference a
// nil Conditions slice.
func (x *{{.Name}}) GetConditions() *[]types.StatusCondition {
	if x == nil || x.Status == nil {
		return nil
	}

	return &x.Status.Conditions
}

// PushCondition appends condition to Status.Conditions and mirrors its
// State onto Status.State, allocating Status or Conditions if needed.
// If condition equals the most recent entry, only its LastTransitionAt
// is updated; no new entry is appended.
func (x *{{.Name}}) PushCondition(condition types.StatusCondition) {
	if x == nil {
		return
	}

	if x.Status == nil {
		x.Status = &{{.StatusTypeRef}}{}
	}

	if x.Status.Conditions == nil {
		x.Status.Conditions = []types.StatusCondition{}
	}

	prevCondition := x.PeekConditions()
	if prevCondition == nil {
		x.Status.Conditions = append(x.Status.Conditions, condition)
		x.Status.State = condition.State
		return
	}

	if common.EqualConditions(*prevCondition, condition) {
		prevCondition.LastTransitionAt = condition.LastTransitionAt
		return
	}

	x.Status.Conditions = append(x.Status.Conditions, condition)
	x.Status.State = condition.State
}

// PopCondition removes the oldest (head) entry from Status.Conditions.
// It is a no-op when the slice is empty or the receiver has no status.
func (x *{{.Name}}) PopCondition() {
	if x == nil || x.Status == nil || len(x.Status.Conditions) == 0 {
		return
	}

	x.Status.Conditions = x.Status.Conditions[1:]
}

// PeekConditions returns a pointer to the most recent (tail) entry in the Status.Conditions.
// If there is no Status or no Conditions in the Status, the function will always
// return nil.
func (x *{{.Name}}) PeekConditions() *types.StatusCondition {
	if x == nil || x.Status == nil || len(x.Status.Conditions) == 0 {
		return nil
	}

	return &x.Status.Conditions[len(x.Status.Conditions)-1]
}

// LenConditions returns the length of Status.Conditions slice,
// or zero if the receiver, its Status, or the slice itself is nil.
func (x *{{.Name}}) LenConditions() int {
	if x == nil || x.Status == nil {
		return 0
	}

	return len(x.Status.Conditions)
}
{{end}}`

type generator struct {
	statusPkgPath string
	tmpl          *template.Template
	header        string
	outFilename   string
}

func newGenerator(headerFile, outFilename string) (*generator, error) {
	header, err := readHeader(headerFile)
	if err != nil {
		return nil, fmt.Errorf("read header: %w", err)
	}
	tmpl, err := template.New("conditions").Parse(fileTemplate)
	if err != nil {
		return nil, fmt.Errorf("parse template: %w", err)
	}
	return &generator{
		statusPkgPath: statusTypesPkgPath,
		tmpl:          tmpl,
		header:        header,
		outFilename:   outFilename,
	}, nil
}

func (g *generator) run(paths []string) error {
	cfg := &packages.Config{
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedSyntax |
			packages.NeedTypes |
			packages.NeedTypesInfo |
			packages.NeedDeps |
			packages.NeedImports,
	}
	pkgs, err := packages.Load(cfg, paths...)
	if err != nil {
		return fmt.Errorf("load packages: %w", err)
	}

	var hadErr bool
	for _, pkg := range pkgs {
		if err := g.processPackage(pkg); err != nil {
			hadErr = true
			log.Printf("conditioned-gen: %s: %v", pkg.PkgPath, err)
		}
	}
	if hadErr {
		return fmt.Errorf("one or more packages failed")
	}
	return nil
}

func readHeader(path string) (string, error) {
	if path == "" {
		return "", nil
	}
	b, err := os.ReadFile(path) // #nosec G304 -- path comes from --header-file CLI flag; caller controls the value //nolint:gosec
	if err != nil {
		return "", err
	}
	return string(b), nil
}

func (g *generator) processPackage(pkg *packages.Package) error {
	if pkg.TypesInfo == nil {
		return fmt.Errorf("missing type info (check package for compile errors)")
	}

	targets, err := g.collectTargets(pkg)
	if err != nil {
		return err
	}
	if len(targets) == 0 {
		return nil
	}
	return g.renderToFile(pkg, targets)
}

func (g *generator) collectTargets(pkg *packages.Package) ([]targetType, error) {
	var targets []targetType
	for _, file := range pkg.Syntax {
		cmap := ast.NewCommentMap(pkg.Fset, file, file.Comments)
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			ts, err := g.collectDeclTargets(pkg, cmap, gen)
			if err != nil {
				return nil, err
			}
			targets = append(targets, ts...)
		}
	}
	return targets, nil
}

func (g *generator) collectDeclTargets(pkg *packages.Package, cmap ast.CommentMap, gen *ast.GenDecl) ([]targetType, error) {
	genComments := cmap[gen]
	var targets []targetType // nolint:prealloc
	for _, spec := range gen.Specs {
		ts, ok := spec.(*ast.TypeSpec)
		if !ok {
			continue
		}
		if !hasMarker(genComments) && !hasMarker(cmap[ts]) {
			continue
		}
		target, err := g.buildTarget(pkg, ts)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", ts.Name.Name, err)
		}
		targets = append(targets, target)
	}
	return targets, nil
}

func (g *generator) renderToFile(pkg *packages.Package, targets []targetType) error {
	var buf bytes.Buffer
	if err := g.tmpl.Execute(&buf, fileData{
		Header:      g.header,
		PackageName: pkg.Name,
		Targets:     targets,
	}); err != nil {
		return fmt.Errorf("render template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format generated source: %w\n--- raw ---\n%s", err, buf.String())
	}

	pkgDir, err := packageDir(pkg)
	if err != nil {
		return err
	}
	outPath := filepath.Join(pkgDir, g.outFilename)
	writeErr := os.WriteFile(outPath, formatted, 0o644) // #nosec G306 -- 0644 is correct for generated source files //nolint:gosec
	if writeErr != nil {
		return fmt.Errorf("write %s: %w", outPath, writeErr)
	}
	return nil
}

func hasMarker(groups []*ast.CommentGroup) bool {
	for _, g := range groups {
		if g == nil {
			continue
		}
		for _, c := range g.List {
			line := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
			if line == marker {
				return true
			}
			if strings.HasPrefix(line, marker+" ") || strings.HasPrefix(line, marker+":") || strings.HasPrefix(line, marker+"=") {
				return true
			}
		}
	}
	return false
}

func (g *generator) buildTarget(pkg *packages.Package, ts *ast.TypeSpec) (targetType, error) {
	structT, err := resolveNamedStruct(pkg, ts)
	if err != nil {
		return targetType{}, err
	}
	namedStatus, err := resolveStatusNamedType(structT, g.statusPkgPath)
	if err != nil {
		return targetType{}, err
	}
	if err := validateStatusStruct(namedStatus, g.statusPkgPath); err != nil {
		return targetType{}, err
	}
	return targetType{
		Name:          ts.Name.Name,
		StatusTypeRef: "types." + namedStatus.Obj().Name(),
	}, nil
}

func resolveNamedStruct(pkg *packages.Package, ts *ast.TypeSpec) (*types.Struct, error) {
	obj := pkg.TypesInfo.Defs[ts.Name]
	if obj == nil {
		return nil, fmt.Errorf("could not resolve type")
	}
	named, ok := obj.Type().(*types.Named)
	if !ok {
		return nil, fmt.Errorf("not a named type")
	}
	structT, ok := named.Underlying().(*types.Struct)
	if !ok {
		return nil, fmt.Errorf("%s marker applied to non-struct type", marker)
	}
	return structT, nil
}

func resolveStatusNamedType(structT *types.Struct, pkgPath string) (*types.Named, error) {
	statusField := findField(structT, "Status")
	if statusField == nil {
		return nil, fmt.Errorf("no Status field; %s requires one", marker)
	}
	statusT := statusField.Type()
	if ptr, ok := statusT.(*types.Pointer); ok {
		statusT = ptr.Elem()
	}
	namedStatus, ok := statusT.(*types.Named)
	if !ok {
		return nil, fmt.Errorf("status field type is not a named type")
	}
	statusObj := namedStatus.Obj()
	if statusObj.Pkg() == nil || statusObj.Pkg().Path() != pkgPath {
		got := "<unknown>"
		if statusObj.Pkg() != nil {
			got = statusObj.Pkg().Path()
		}
		return nil, fmt.Errorf("status field type must live in %s, got %s", pkgPath, got)
	}
	return namedStatus, nil
}

func validateStatusStruct(namedStatus *types.Named, pkgPath string) error {
	statusObj := namedStatus.Obj()
	statusStruct, ok := namedStatus.Underlying().(*types.Struct)
	if !ok {
		return fmt.Errorf("status type %s is not a struct", statusObj.Name())
	}
	condField := findField(statusStruct, "Conditions")
	if condField == nil {
		return fmt.Errorf("status type %s has no Conditions field", statusObj.Name())
	}
	slice, ok := condField.Type().(*types.Slice)
	if !ok {
		return fmt.Errorf("status type %s Conditions field is not a slice", statusObj.Name())
	}
	elem, ok := slice.Elem().(*types.Named)
	if !ok {
		return fmt.Errorf("status type %s Conditions element is not a named type", statusObj.Name())
	}
	elemObj := elem.Obj()
	if elemObj.Pkg() == nil || elemObj.Pkg().Path() != pkgPath || elemObj.Name() != "StatusCondition" {
		return fmt.Errorf("status type %s Conditions element must be %s.StatusCondition", statusObj.Name(), pkgPath)
	}
	if findField(statusStruct, "State") == nil {
		return fmt.Errorf("status type %s has no State field", statusObj.Name())
	}
	return nil
}

func findField(s *types.Struct, name string) *types.Var {
	for i := 0; i < s.NumFields(); i++ {
		f := s.Field(i)
		if f.Name() == name {
			return f
		}
	}
	return nil
}

func packageDir(pkg *packages.Package) (string, error) {
	if len(pkg.GoFiles) > 0 {
		return filepath.Dir(pkg.GoFiles[0]), nil
	}
	if len(pkg.CompiledGoFiles) > 0 {
		return filepath.Dir(pkg.CompiledGoFiles[0]), nil
	}
	return "", fmt.Errorf("could not determine package directory for %s", pkg.PkgPath)
}
