package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
	"golang.org/x/tools/go/packages"
)

const (
	marker             = "+ecp:conditioned"
	statusTypesPkgPath = "github.com/eu-sovereign-cloud/ecp/foundation/persistence/generated/types"
)

type targetType struct {
	Name          string
	StatusTypeRef string
}

type fileData struct {
	Header      string
	PackageName string
	Targets     []targetType
}

const fileTemplate = `//go:build !ignore_autogenerated

{{.Header}}// Code generated by conditioned-gen. DO NOT EDIT.

package {{.PackageName}}

import (
	genv1 "github.com/eu-sovereign-cloud/ecp/foundation/persistence/generated/types"
	"github.com/eu-sovereign-cloud/ecp/foundation/persistence/regional/common"
)
{{range .Targets}}
// Compile-time assertion that *{{.Name}} satisfies common.Conditioned.
var _ common.Conditioned = (*{{.Name}})(nil)

// GetStatusConditions returns a pointer to the Status.Conditions slice, or nil
// if the receiver, its Status, or the slice itself is nil.
func (x *{{.Name}}) GetStatusConditions() *[]genv1.StatusCondition {
	if x == nil || x.Status == nil {
		return nil
	}

	return &x.Status.Conditions
}

// PushStatusCondition appends condition to Status.Conditions and mirrors its
// State onto Status.State, allocating Status or Conditions if needed.
func (x *{{.Name}}) PushStatusCondition(condition genv1.StatusCondition) {
	if x == nil {
		return
	}

	if x.Status == nil {
		x.Status = &{{.StatusTypeRef}}{}
	}

	if x.Status.Conditions == nil {
		x.Status.Conditions = []genv1.StatusCondition{}
	}

	x.Status.Conditions = append(x.Status.Conditions, condition)
	x.Status.State = condition.State
}

// PopStatusCondition removes the oldest (head) entry from Status.Conditions.
// It is a no-op when the slice is empty or the receiver has no status.
func (x *{{.Name}}) PopStatusCondition() {
	if x == nil || x.Status == nil || len(x.Status.Conditions) == 0 {
		return
	}

	x.Status.Conditions = x.Status.Conditions[1:]
}

// LenStatusConditions returns the length of Status.Conditions slice, 
// or zero if the receiver, its Status, or the slice itself is nil.
func (x *{{.Name}}) LenStatusConditions() int {
	if x == nil || x.Status == nil {
		return 0
	}

	return len(x.Status.Conditions)
}
{{end}}`

func main() {
	var (
		paths       []string
		headerFile  string
		outFilename string
	)

	cmd := &cobra.Command{
		Use:   "conditioned-gen",
		Short: "Generate Conditioned interface methods for +ecp:conditioned-marked types",
		RunE: func(cmd *cobra.Command, args []string) error {
			return run(paths, headerFile, outFilename)
		},
	}

	cmd.Flags().StringSliceVar(&paths, "paths", nil,
		"package path pattern(s) to process; may be repeated or comma-separated (e.g. ./v1/...)")
	cmd.Flags().StringVar(&headerFile, "header-file", "",
		"path to a boilerplate header file to prepend to generated files")
	cmd.Flags().StringVar(&outFilename, "output-filename", "zz_generated.conditions.go",
		"name of the generated file written into each target package")

	if err := cmd.Execute(); err != nil {
		os.Exit(1)
	}
}

func run(paths []string, headerFile, outFilename string) error {
	if len(paths) == 0 {
		return fmt.Errorf("at least one --paths value is required")
	}

	header, err := readHeader(headerFile)
	if err != nil {
		return fmt.Errorf("read header: %w", err)
	}

	tmpl, err := template.New("conditions").Parse(fileTemplate)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	cfg := &packages.Config{
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedSyntax |
			packages.NeedTypes |
			packages.NeedTypesInfo |
			packages.NeedDeps |
			packages.NeedImports,
	}
	pkgs, err := packages.Load(cfg, paths...)
	if err != nil {
		return fmt.Errorf("load packages: %w", err)
	}

	var hadErr bool
	for _, pkg := range pkgs {
		if err := processPackage(pkg, tmpl, header, outFilename); err != nil {
			hadErr = true
			log.Printf("conditioned-gen: %s: %v", pkg.PkgPath, err)
		}
	}
	if hadErr {
		return fmt.Errorf("one or more packages failed")
	}
	return nil
}

func readHeader(path string) (string, error) {
	if path == "" {
		return "", nil
	}
	b, err := os.ReadFile(path) //nolint:gosec
	if err != nil {
		return "", err
	}
	return string(b), nil
}

func processPackage(pkg *packages.Package, tmpl *template.Template, header, outFilename string) error {
	if pkg.TypesInfo == nil {
		return fmt.Errorf("missing type info (check package for compile errors)")
	}

	var targets []targetType
	for _, file := range pkg.Syntax {
		cmap := ast.NewCommentMap(pkg.Fset, file, file.Comments)
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			genComments := cmap[gen]
			for _, spec := range gen.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				specComments := cmap[ts]
				if !hasMarker(genComments) && !hasMarker(specComments) {
					continue
				}
				target, err := buildTarget(pkg, ts)
				if err != nil {
					return fmt.Errorf("%s: %w", ts.Name.Name, err)
				}
				targets = append(targets, target)
			}
		}
	}

	if len(targets) == 0 {
		return nil
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, fileData{
		Header:      header,
		PackageName: pkg.Name,
		Targets:     targets,
	}); err != nil {
		return fmt.Errorf("render template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format generated source: %w\n--- raw ---\n%s", err, buf.String())
	}

	pkgDir, err := packageDir(pkg)
	if err != nil {
		return err
	}
	outPath := filepath.Join(pkgDir, outFilename)
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil { //nolint:gosec
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	return nil
}

func hasMarker(groups []*ast.CommentGroup) bool {
	for _, g := range groups {
		if g == nil {
			continue
		}
		for _, c := range g.List {
			line := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
			if line == marker {
				return true
			}
			if strings.HasPrefix(line, marker+" ") || strings.HasPrefix(line, marker+":") || strings.HasPrefix(line, marker+"=") {
				return true
			}
		}
	}
	return false
}

func buildTarget(pkg *packages.Package, ts *ast.TypeSpec) (targetType, error) {
	obj := pkg.TypesInfo.Defs[ts.Name]
	if obj == nil {
		return targetType{}, fmt.Errorf("could not resolve type")
	}
	named, ok := obj.Type().(*types.Named)
	if !ok {
		return targetType{}, fmt.Errorf("not a named type")
	}
	structT, ok := named.Underlying().(*types.Struct)
	if !ok {
		return targetType{}, fmt.Errorf("%s marker applied to non-struct type", marker)
	}

	statusField := findField(structT, "Status")
	if statusField == nil {
		return targetType{}, fmt.Errorf("no Status field; %s requires one", marker)
	}

	statusT := statusField.Type()
	if ptr, ok := statusT.(*types.Pointer); ok {
		statusT = ptr.Elem()
	}
	namedStatus, ok := statusT.(*types.Named)
	if !ok {
		return targetType{}, fmt.Errorf("status field type is not a named type")
	}
	statusObj := namedStatus.Obj()
	if statusObj.Pkg() == nil || statusObj.Pkg().Path() != statusTypesPkgPath {
		got := "<unknown>"
		if statusObj.Pkg() != nil {
			got = statusObj.Pkg().Path()
		}
		return targetType{}, fmt.Errorf("status field type must live in %s, got %s", statusTypesPkgPath, got)
	}

	statusStruct, ok := namedStatus.Underlying().(*types.Struct)
	if !ok {
		return targetType{}, fmt.Errorf("status type %s is not a struct", statusObj.Name())
	}
	condField := findField(statusStruct, "Conditions")
	if condField == nil {
		return targetType{}, fmt.Errorf("status type %s has no Conditions field", statusObj.Name())
	}
	slice, ok := condField.Type().(*types.Slice)
	if !ok {
		return targetType{}, fmt.Errorf("status type %s Conditions field is not a slice", statusObj.Name())
	}
	elem, ok := slice.Elem().(*types.Named)
	if !ok {
		return targetType{}, fmt.Errorf("status type %s Conditions element is not a named type", statusObj.Name())
	}
	elemObj := elem.Obj()
	if elemObj.Pkg() == nil || elemObj.Pkg().Path() != statusTypesPkgPath || elemObj.Name() != "StatusCondition" {
		return targetType{}, fmt.Errorf("status type %s Conditions element must be %s.StatusCondition", statusObj.Name(), statusTypesPkgPath)
	}

	if findField(statusStruct, "State") == nil {
		return targetType{}, fmt.Errorf("status type %s has no State field", statusObj.Name())
	}

	return targetType{
		Name:          ts.Name.Name,
		StatusTypeRef: "genv1." + statusObj.Name(),
	}, nil
}

func findField(s *types.Struct, name string) *types.Var {
	for i := 0; i < s.NumFields(); i++ {
		f := s.Field(i)
		if f.Name() == name {
			return f
		}
	}
	return nil
}

func packageDir(pkg *packages.Package) (string, error) {
	if len(pkg.GoFiles) > 0 {
		return filepath.Dir(pkg.GoFiles[0]), nil
	}
	if len(pkg.CompiledGoFiles) > 0 {
		return filepath.Dir(pkg.CompiledGoFiles[0]), nil
	}
	return "", fmt.Errorf("could not determine package directory for %s", pkg.PkgPath)
}
