//go:build crdgen

package authorization

//go:generate go run ../../../cmd/conditioned-gen --header-file=../../../../../../.github/boilerplate.go.txt --paths=./roles/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile=../../../../../../.github/boilerplate.go.txt paths=./roles/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen crd paths=./roles/v1/... output:crd:artifacts:config=../../../generated/crds/authorization

//go:generate go run ../../../cmd/conditioned-gen --header-file=../../../../../../.github/boilerplate.go.txt --paths=./role-assignments/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile=../../../../../../.github/boilerplate.go.txt paths=./role-assignments/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen crd paths=./role-assignments/v1/... output:crd:artifacts:config=../../../generated/crds/authorization
