//go:build !ignore_autogenerated

// Copyright (c) 2025 The ECP Authors
// SPDX-License-Identifier: Apache-2.0
//
// Code generated by conditioned-gen. DO NOT EDIT.

package kubernetes

import (
	genv1 "github.com/eu-sovereign-cloud/ecp/framework/persistence/kubernetes/schema/v1"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var _ genv1.Conditioned = (*SecurityGroupRule)(nil)

func (x *SecurityGroupRule) GetConditions() []genv1.StatusCondition {
	if x == nil || x.Status == nil {
		return nil
	}
	return x.Status.Conditions
}

func (x *SecurityGroupRule) PushCondition(condition genv1.StatusCondition) {
	if x == nil {
		return
	}
	if x.Status == nil {
		x.Status = &genv1.Status{}
	}
	if x.Status.Conditions == nil {
		x.Status.Conditions = []genv1.StatusCondition{}
	}
	if condition.LastTransitionAt.IsZero() {
		condition.LastTransitionAt = metav1.Now()
	}
	prevCondition := x.PeekConditions()
	if prevCondition == nil {
		condition.Occurrences = 1
		x.Status.Conditions = append([]genv1.StatusCondition{condition}, x.Status.Conditions...)
		x.Status.State = condition.State
		return
	}
	if genv1.EqualConditions(*prevCondition, condition) {
		prevCondition.LastTransitionAt = condition.LastTransitionAt
		prevCondition.Occurrences++
		return
	}
	condition.Occurrences = 1
	x.Status.Conditions = append([]genv1.StatusCondition{condition}, x.Status.Conditions...)
	x.Status.State = condition.State
}

func (x *SecurityGroupRule) PopCondition() {
	if x == nil || x.Status == nil || len(x.Status.Conditions) == 0 {
		return
	}
	x.Status.Conditions = x.Status.Conditions[:len(x.Status.Conditions)-1]
}

func (x *SecurityGroupRule) PeekConditions() *genv1.StatusCondition {
	if x == nil || x.Status == nil || len(x.Status.Conditions) == 0 {
		return nil
	}
	return &x.Status.Conditions[0]
}

func (x *SecurityGroupRule) LenConditions() int {
	if x == nil || x.Status == nil {
		return 0
	}
	return len(x.Status.Conditions)
}
