// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/resource/authorization/role-assignment/v1/backend/kubernetes (interfaces: RoleAssignmentPlugin)
//
// Generated by this command:
//
//	mockgen -package kubernetes_test -destination ./zz_mock_plugin_test.go github.com/eu-sovereign-cloud/ecp/resource/authorization/role-assignment/v1/backend/kubernetes RoleAssignmentPlugin
//

// Package kubernetes_test is a generated GoMock package.
package kubernetes_test

import (
	context "context"
	reflect "reflect"

	v1 "github.com/eu-sovereign-cloud/ecp/resource/authorization/role-assignment/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleAssignmentPlugin is a mock of RoleAssignmentPlugin interface.
type MockRoleAssignmentPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockRoleAssignmentPluginMockRecorder
	isgomock struct{}
}

// MockRoleAssignmentPluginMockRecorder is the mock recorder for MockRoleAssignmentPlugin.
type MockRoleAssignmentPluginMockRecorder struct {
	mock *MockRoleAssignmentPlugin
}

// NewMockRoleAssignmentPlugin creates a new mock instance.
func NewMockRoleAssignmentPlugin(ctrl *gomock.Controller) *MockRoleAssignmentPlugin {
	mock := &MockRoleAssignmentPlugin{ctrl: ctrl}
	mock.recorder = &MockRoleAssignmentPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleAssignmentPlugin) EXPECT() *MockRoleAssignmentPluginMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoleAssignmentPlugin) Create(ctx context.Context, resource *v1.RoleAssignment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoleAssignmentPluginMockRecorder) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoleAssignmentPlugin)(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockRoleAssignmentPlugin) Delete(ctx context.Context, resource *v1.RoleAssignment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRoleAssignmentPluginMockRecorder) Delete(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoleAssignmentPlugin)(nil).Delete), ctx, resource)
}
