// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/resource/storage/v1/image/backend/kubernetes (interfaces: DependencyResolver)
//
// Generated by this command:
//
//	mockgen -package kubernetes_test -destination ./zz_mock_deps_test.go github.com/eu-sovereign-cloud/ecp/resource/storage/v1/image/backend/kubernetes DependencyResolver
//

// Package kubernetes_test is a generated GoMock package.
package kubernetes_test

import (
	context "context"
	reflect "reflect"

	domain "github.com/eu-sovereign-cloud/ecp/resource/common/domain"
	gomock "go.uber.org/mock/gomock"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// MockDependencyResolver is a mock of DependencyResolver interface.
type MockDependencyResolver struct {
	ctrl     *gomock.Controller
	recorder *MockDependencyResolverMockRecorder
	isgomock struct{}
}

// MockDependencyResolverMockRecorder is the mock recorder for MockDependencyResolver.
type MockDependencyResolverMockRecorder struct {
	mock *MockDependencyResolver
}

// NewMockDependencyResolver creates a new mock instance.
func NewMockDependencyResolver(ctrl *gomock.Controller) *MockDependencyResolver {
	mock := &MockDependencyResolver{ctrl: ctrl}
	mock.recorder = &MockDependencyResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDependencyResolver) EXPECT() *MockDependencyResolverMockRecorder {
	return m.recorder
}

// State mocks base method.
func (m *MockDependencyResolver) State(ctx context.Context, gvr schema.GroupVersionResource, ref domain.Reference, defaultTenant string) (bool, domain.ResourceState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "State", ctx, gvr, ref, defaultTenant)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(domain.ResourceState)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// State indicates an expected call of State.
func (mr *MockDependencyResolverMockRecorder) State(ctx, gvr, ref, defaultTenant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "State", reflect.TypeOf((*MockDependencyResolver)(nil).State), ctx, gvr, ref, defaultTenant)
}
