// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/resource/network/v1/subnet/backend/kubernetes (interfaces: SubnetPlugin)
//
// Generated by this command:
//
//	mockgen -package kubernetes_test -destination ./zz_mock_plugin_test.go github.com/eu-sovereign-cloud/ecp/resource/network/v1/subnet/backend/kubernetes SubnetPlugin
//

// Package kubernetes_test is a generated GoMock package.
package kubernetes_test

import (
	context "context"
	reflect "reflect"

	subnet "github.com/eu-sovereign-cloud/ecp/resource/network/v1/subnet"
	gomock "go.uber.org/mock/gomock"
)

// MockSubnetPlugin is a mock of SubnetPlugin interface.
type MockSubnetPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockSubnetPluginMockRecorder
	isgomock struct{}
}

// MockSubnetPluginMockRecorder is the mock recorder for MockSubnetPlugin.
type MockSubnetPluginMockRecorder struct {
	mock *MockSubnetPlugin
}

// NewMockSubnetPlugin creates a new mock instance.
func NewMockSubnetPlugin(ctrl *gomock.Controller) *MockSubnetPlugin {
	mock := &MockSubnetPlugin{ctrl: ctrl}
	mock.recorder = &MockSubnetPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubnetPlugin) EXPECT() *MockSubnetPluginMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSubnetPlugin) Create(ctx context.Context, resource *subnet.Subnet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSubnetPluginMockRecorder) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubnetPlugin)(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockSubnetPlugin) Delete(ctx context.Context, resource *subnet.Subnet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSubnetPluginMockRecorder) Delete(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSubnetPlugin)(nil).Delete), ctx, resource)
}

// Update mocks base method.
func (m *MockSubnetPlugin) Update(ctx context.Context, resource *subnet.Subnet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSubnetPluginMockRecorder) Update(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSubnetPlugin)(nil).Update), ctx, resource)
}
