// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package schema

import (
	"encoding/json"
	"time"
)

// Extensions User-defined key/value pairs — map[string]interface{} becomes map[string]string.
type Extensions map[string]interface{}

// ResourceMetadata contains time.Time fields that become metav1.Time.
type ResourceMetadata struct {
	CreatedAt      time.Time  `json:"createdAt"`
	DeletedAt      *time.Time `json:"deletedAt,omitempty"`
	LastModifiedAt time.Time  `json:"lastModifiedAt"`
}

// RequestBody has a union field with no tag — should get json:"-" added.
type RequestBody struct {
	Name  string          `json:"name"`
	union json.RawMessage
}

// StatusCondition gets an Occurrences int field appended.
type StatusCondition struct {
	LastTransitionAt time.Time `json:"lastTransitionAt"`
	Message          string    `json:"message"`
	State            string    `json:"state,omitempty"`
	Type             string    `json:"type"`
}
