// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/foundation/plugin/aruba/pkg/port/repository (interfaces: Repository,Writer,Watcher,Reader)
//
// Generated by this command:
//
//	mockgen -package=handler -destination=./zz_mock_workspace_repository.go github.com/eu-sovereign-cloud/ecp/foundation/plugin/aruba/pkg/port/repository Repository,Writer,Watcher,Reader
//

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	reflect "reflect"

	repository "github.com/eu-sovereign-cloud/ecp/foundation/plugin/aruba/pkg/port/repository"
	gomock "go.uber.org/mock/gomock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockRepository is a mock of Repository interface.
type MockRepository[T any, L any] struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder[T, L]
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder[T any, L any] struct {
	mock *MockRepository[T, L]
}

// NewMockRepository creates a new mock instance.
func NewMockRepository[T any, L any](ctrl *gomock.Controller) *MockRepository[T, L] {
	mock := &MockRepository[T, L]{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder[T, L]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository[T, L]) EXPECT() *MockRepositoryMockRecorder[T, L] {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository[T, L]) Create(ctx context.Context, resource T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder[T, L]) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository[T, L])(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockRepository[T, L]) Delete(ctx context.Context, resource T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder[T, L]) Delete(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository[T, L])(nil).Delete), ctx, resource)
}

// List mocks base method.
func (m *MockRepository[T, L]) List(ctx context.Context, opts ...client.ListOption) (L, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(L)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder[T, L]) List(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository[T, L])(nil).List), varargs...)
}

// Load mocks base method.
func (m *MockRepository[T, L]) Load(ctx context.Context, resource T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockRepositoryMockRecorder[T, L]) Load(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockRepository[T, L])(nil).Load), ctx, resource)
}

// Update mocks base method.
func (m *MockRepository[T, L]) Update(ctx context.Context, resource T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder[T, L]) Update(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository[T, L])(nil).Update), ctx, resource)
}

// WaitUntil mocks base method.
func (m *MockRepository[T, L]) WaitUntil(ctx context.Context, resource T, condition repository.WaitConditionFunc[T]) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitUntil", ctx, resource, condition)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitUntil indicates an expected call of WaitUntil.
func (mr *MockRepositoryMockRecorder[T, L]) WaitUntil(ctx, resource, condition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitUntil", reflect.TypeOf((*MockRepository[T, L])(nil).WaitUntil), ctx, resource, condition)
}

// Watch mocks base method.
func (m *MockRepository[T, L]) Watch(ctx context.Context, resource T) (chan T, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", ctx, resource)
	ret0, _ := ret[0].(chan T)
	ret1, _ := ret[1].(func())
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Watch indicates an expected call of Watch.
func (mr *MockRepositoryMockRecorder[T, L]) Watch(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockRepository[T, L])(nil).Watch), ctx, resource)
}

// MockWriter is a mock of Writer interface.
type MockWriter[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder[T]
	isgomock struct{}
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder[T any] struct {
	mock *MockWriter[T]
}

// NewMockWriter creates a new mock instance.
func NewMockWriter[T any](ctrl *gomock.Controller) *MockWriter[T] {
	mock := &MockWriter[T]{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter[T]) EXPECT() *MockWriterMockRecorder[T] {
	return m.recorder
}

// Create mocks base method.
func (m *MockWriter[T]) Create(ctx context.Context, resource T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWriterMockRecorder[T]) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWriter[T])(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockWriter[T]) Delete(ctx context.Context, resource T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWriterMockRecorder[T]) Delete(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWriter[T])(nil).Delete), ctx, resource)
}

// Update mocks base method.
func (m *MockWriter[T]) Update(ctx context.Context, resource T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWriterMockRecorder[T]) Update(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWriter[T])(nil).Update), ctx, resource)
}

// MockWatcher is a mock of Watcher interface.
type MockWatcher[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockWatcherMockRecorder[T]
	isgomock struct{}
}

// MockWatcherMockRecorder is the mock recorder for MockWatcher.
type MockWatcherMockRecorder[T any] struct {
	mock *MockWatcher[T]
}

// NewMockWatcher creates a new mock instance.
func NewMockWatcher[T any](ctrl *gomock.Controller) *MockWatcher[T] {
	mock := &MockWatcher[T]{ctrl: ctrl}
	mock.recorder = &MockWatcherMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatcher[T]) EXPECT() *MockWatcherMockRecorder[T] {
	return m.recorder
}

// WaitUntil mocks base method.
func (m *MockWatcher[T]) WaitUntil(ctx context.Context, resource T, condition repository.WaitConditionFunc[T]) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitUntil", ctx, resource, condition)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitUntil indicates an expected call of WaitUntil.
func (mr *MockWatcherMockRecorder[T]) WaitUntil(ctx, resource, condition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitUntil", reflect.TypeOf((*MockWatcher[T])(nil).WaitUntil), ctx, resource, condition)
}

// Watch mocks base method.
func (m *MockWatcher[T]) Watch(ctx context.Context, resource T) (chan T, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", ctx, resource)
	ret0, _ := ret[0].(chan T)
	ret1, _ := ret[1].(func())
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Watch indicates an expected call of Watch.
func (mr *MockWatcherMockRecorder[T]) Watch(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockWatcher[T])(nil).Watch), ctx, resource)
}

// MockReader is a mock of Reader interface.
type MockReader[T any, L any] struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder[T, L]
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder[T any, L any] struct {
	mock *MockReader[T, L]
}

// NewMockReader creates a new mock instance.
func NewMockReader[T any, L any](ctrl *gomock.Controller) *MockReader[T, L] {
	mock := &MockReader[T, L]{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder[T, L]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader[T, L]) EXPECT() *MockReaderMockRecorder[T, L] {
	return m.recorder
}

// List mocks base method.
func (m *MockReader[T, L]) List(ctx context.Context, opts ...client.ListOption) (L, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(L)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockReaderMockRecorder[T, L]) List(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockReader[T, L])(nil).List), varargs...)
}

// Load mocks base method.
func (m *MockReader[T, L]) Load(ctx context.Context, resource T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockReaderMockRecorder[T, L]) Load(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockReader[T, L])(nil).Load), ctx, resource)
}
