// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package kubernetes

// +kubebuilder:object:generate=true
// +kubebuilder:object:root=false

import genv1 "github.com/eu-sovereign-cloud/ecp/framework/persistence/kubernetes/schema/v1"

// PublicIp defines model for PublicIp.

// Annotations User-defined key/value pairs that are mutable and can be used to add annotations.
// The number of annotations is eventually limited by the CSP.

// Extensions User-defined key/value pairs that are mutable and can be used to add extensions.
// Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.

// Labels User-defined key/value pairs that are mutable and can be used to
// organize and categorize resources. They can be used to filter resources.
// The number of labels is eventually limited by the CSP.

// Metadata Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.

// Spec Specification of the public IP.

// Status Status of the public IP.

// PublicIpSpec Specification of the public IP.
type PublicIpSpec struct {
	// Address The public IP address in case of BYOIP.
	Address string `json:"address,omitempty" x-cel-message-0:"spec.address must be a valid IPv4/IPv6 address" x-cel-rule-0:"self.size() == 0 || isIP(self)" x-kubebuilder-validation-max-length:"39"`

	// Version IP version of the address
	Version genv1.IPVersion `json:"version" x-kubebuilder-validation-enum:"IPv4;IPv6"`
}

// PublicIpStatus defines model for PublicIpStatus.
type PublicIpStatus struct {
	// AttachedTo Reference to the instance the public IP is attached to.
	AttachedTo *genv1.Reference        `json:"attachedTo,omitempty"`
	Conditions []genv1.StatusCondition `json:"conditions" x-kubebuilder-validation-max-items:"32"`

	// IpAddress The public IP address in case of BYOIP.
	IpAddress string              `json:"ipAddress,omitempty" x-cel-message-0:"status.ipAddress must be a valid IPv4/IPv6 address" x-cel-rule-0:"self.size() == 0 || isIP(self)" x-kubebuilder-validation-max-length:"39"`
	State     genv1.ResourceState `json:"state,omitempty"`
}
