---
apiVersion: v1
kind: Namespace
metadata:
  name: seca
---
apiVersion: storage.v1.secapi.cloud/v1
kind: StorageSKU
metadata:
  labels:
    secapi.cloud/tenant-id: seca
  name: fast-local
  namespace: seca
spec:
  iops: 10000
  minVolumeSize: 10
  type: local-ephemeral