// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package kubernetes

// +kubebuilder:object:generate=true
// +kubebuilder:object:root=false

import schemav1 "github.com/eu-sovereign-cloud/ecp/framework/persistence/kubernetes/schema/v1"

// SecurityGroupRuleSpecDirection Direction of the traffic flow.
type SecurityGroupRuleSpecDirection string

// SecurityGroupRuleSpecProtocol Network protocol for the rule.
type SecurityGroupRuleSpecProtocol string

// SecurityGroupRuleStatus Current status of the resource
type SecurityGroupRuleStatus = schemav1.Status

// SecurityGroupRuleSpec Specification of a security group rule defining network access permissions.
type SecurityGroupRuleSpec struct {
	// Annotations User-defined key/value pairs that are mutable and can be used to add annotations.
	Annotations schemav1.Annotations `json:"annotations,omitempty"`

	// Direction Direction of the traffic flow
	Direction SecurityGroupRuleSpecDirection `json:"direction"`

	// Icmp ICMP specific rule configuration
	Icmp *IcmpConfig `json:"icmp,omitempty"`

	// Ports Defines a specific port list or port range for the rule.
	Ports *Ports `json:"ports,omitempty"`

	// Protocol Network protocol for the rule
	Protocol SecurityGroupRuleSpecProtocol `json:"protocol,omitempty"`

	// SourceRef Reference to a CIDR block, IP address, gateway, instance or security group
	SourceRef []schemav1.Reference `json:"sourceRef,omitempty"`

	Version schemav1.IPVersion `json:"version,omitempty"`
}

// IcmpConfig ICMP specific rule configuration
type IcmpConfig struct {
	Code int `json:"code"`
	Type int `json:"type"`
}

// Port A valid network port number.
type Port = int

// Ports Defines a specific port list or port range for the rule.
type Ports struct {
	From Port   `json:"from,omitempty"`
	List []Port `json:"list,omitempty"`
	To   Port   `json:"to,omitempty"`
}

// SecurityGroup defines model for SecurityGroup.

// Annotations User-defined key/value pairs that are mutable and can be used to add annotations.
// The number of annotations is eventually limited by the CSP.

// Extensions User-defined key/value pairs that are mutable and can be used to add extensions.
// Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.

// Labels User-defined key/value pairs that are mutable and can be used to
// organize and categorize resources. They can be used to filter resources.
// The number of labels is eventually limited by the CSP.

// Metadata Metadata for regional resources with name, permission, modification, type, tenant and workspace and region information.

// Spec Specification of the security group

// Status Status of the security group, including the status of its rules.
// The status is read-only and reflects the current state of the security group.

// SecurityGroupSpec Specification of the security group
type SecurityGroupSpec struct {
	// RuleRefs References to shared SecurityGroupRule resources.
	// These rules are applied in addition to the inline rules.
	RuleRefs []schemav1.Reference `json:"ruleRefs,omitempty" x-kubebuilder-validation-max-items:"500"`

	// Rules Network access rules defining communication between security groups and external networks.
	//
	// Rule Evaluation:
	// - Default behavior is to deny all traffic not explicitly allowed
	// - Rules provide granular control over allowed traffic types, sources, and destinations
	Rules []SecurityGroupRuleSpec `json:"rules,omitempty" x-kubebuilder-validation-max-items:"500"`
}

// SecurityGroupStatus defines model for SecurityGroupStatus.
type SecurityGroupStatus struct {
	Conditions []schemav1.StatusCondition `json:"conditions" x-kubebuilder-validation-max-items:"32"`
	Rules      []SecurityGroupRuleStatus  `json:"rules,omitempty" x-kubebuilder-validation-max-items:"500"`
	State      schemav1.ResourceState     `json:"state,omitempty"`
}
