{{- if and .Values.gatewayGlobal.enabled .Values.gatewayGlobal.ingress.enabled }}
{{- $fullName := include "ecp.gatewayGlobal.fullname" . }}
{{- $svcPort := .Values.gatewayGlobal.service.port }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "ecp.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway-global
  {{- with .Values.gatewayGlobal.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.gatewayGlobal.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.gatewayGlobal.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.gatewayGlobal.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
