//go:build crdgen

package network

//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile=../../../../../../.github/boilerplate.go.txt paths=./skus/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen crd paths=./skus/v1/... output:crd:artifacts:config=../../../generated/crds/network

//go:generate go run ../../../cmd/conditioned-gen --header-file=../../../../../../.github/boilerplate.go.txt --paths=./networks/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile=../../../../../../.github/boilerplate.go.txt paths=./networks/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen crd paths=./networks/v1/... output:crd:artifacts:config=../../../generated/crds/network

//go:generate go run ../../../cmd/conditioned-gen --header-file=../../../../../../.github/boilerplate.go.txt --paths=./security-groups/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile=../../../../../../.github/boilerplate.go.txt paths=./security-groups/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen crd paths=./security-groups/v1/... output:crd:artifacts:config=../../../generated/crds/network

//go:generate go run ../../../cmd/conditioned-gen --header-file=../../../../../../.github/boilerplate.go.txt --paths=./security-group-rules/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile=../../../../../../.github/boilerplate.go.txt paths=./security-group-rules/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen crd paths=./security-group-rules/v1/... output:crd:artifacts:config=../../../generated/crds/network

//go:generate go run ../../../cmd/conditioned-gen --header-file=../../../../../../.github/boilerplate.go.txt --paths=./subnets/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile=../../../../../../.github/boilerplate.go.txt paths=./subnets/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen crd paths=./subnets/v1/... output:crd:artifacts:config=../../../generated/crds/network

//go:generate go run ../../../cmd/conditioned-gen --header-file=../../../../../../.github/boilerplate.go.txt --paths=./nics/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile=../../../../../../.github/boilerplate.go.txt paths=./nics/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen crd paths=./nics/v1/... output:crd:artifacts:config=../../../generated/crds/network

//go:generate go run ../../../cmd/conditioned-gen --header-file=../../../../../../.github/boilerplate.go.txt --paths=./public-ips/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile=../../../../../../.github/boilerplate.go.txt paths=./public-ips/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen crd paths=./public-ips/v1/... output:crd:artifacts:config=../../../generated/crds/network

//go:generate go run ../../../cmd/conditioned-gen --header-file=../../../../../../.github/boilerplate.go.txt --paths=./internet-gateways/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile=../../../../../../.github/boilerplate.go.txt paths=./internet-gateways/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen crd paths=./internet-gateways/v1/... output:crd:artifacts:config=../../../generated/crds/network

//go:generate go run ../../../cmd/conditioned-gen --header-file=../../../../../../.github/boilerplate.go.txt --paths=./route-tables/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile=../../../../../../.github/boilerplate.go.txt paths=./route-tables/v1/...
//go:generate go run sigs.k8s.io/controller-tools/cmd/controller-gen crd paths=./route-tables/v1/... output:crd:artifacts:config=../../../generated/crds/network
