package middleware

import "net/http"

// Chain converts a list of standard middleware functions into the typed slice
// expected by oapi-codegen's StdHTTPServerOptions.Middlewares.
//
// IMPORTANT — oapi-codegen ordering gotcha: oapi-codegen wraps middlewares from
// the END of the Middlewares slice outward, so the LAST entry runs FIRST (outermost).
// Chain reverses the provided functions so callers can pass them in natural
// execution order (left-to-right = outer-to-inner = first executed first):
//
//	opts.Middlewares = middleware.Chain[sdknetworkapi.MiddlewareFunc](
//	    middleware.NewAuthentication(authn, log),  // runs first: validates bearer token
//	    middleware.NewAuthorization(checker, extract, log), // runs second: enforces RBAC
//	)
//
// The type parameter M must be a function type assignable from
// func(http.Handler) http.Handler, which is the shape generated by oapi-codegen for
// every provider's MiddlewareFunc alias.
func Chain[M ~func(http.Handler) http.Handler](mws ...func(http.Handler) http.Handler) []M {
	// Reverse so that oapi-codegen's inside-out wrapping produces the expected
	// execution order: first element in mws runs outermost (first executed).
	n := len(mws)
	result := make([]M, n)
	for i, mw := range mws {
		result[n-1-i] = M(mw)
	}
	return result
}
