//go:build !ignore_autogenerated

// Copyright (c) 2025 The ECP Authors
// SPDX-License-Identifier: Apache-2.0
//
// Code generated by controller-gen. DO NOT EDIT.

package kubernetes

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *InstanceSku) DeepCopyInto(out *InstanceSku) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

func (in *InstanceSku) DeepCopy() *InstanceSku {
	if in == nil {
		return nil
	}
	out := new(InstanceSku)
	in.DeepCopyInto(out)
	return out
}

func (in *InstanceSku) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *InstanceSkuList) DeepCopyInto(out *InstanceSkuList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InstanceSku, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *InstanceSkuList) DeepCopy() *InstanceSkuList {
	if in == nil {
		return nil
	}
	out := new(InstanceSkuList)
	in.DeepCopyInto(out)
	return out
}

func (in *InstanceSkuList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
