// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package kubernetes

// +kubebuilder:object:generate=true
// +kubebuilder:object:root=false

import schemav1 "github.com/eu-sovereign-cloud/ecp/framework/persistence/kubernetes/schema/v1"

// Workspace defines model for Workspace.

// Annotations User-defined key/value pairs that are mutable and can be used to add annotations.
// The number of annotations is eventually limited by the CSP.

// Extensions User-defined key/value pairs that are mutable and can be used to add extensions.
// Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.

// Labels User-defined key/value pairs that are mutable and can be used to
// organize and categorize resources. They can be used to filter resources.
// The number of labels is eventually limited by the CSP.

// Metadata Metadata for regional resources with name, permission, modification, type, tenant and region information.

// Spec Specification of the workspace, including its capabilities and extensions.

// Status Status of the workspace, including the number of resources in the workspace.

// WorkspaceSpec Specification of the workspace, including its capabilities and extensions.
type WorkspaceSpec = map[string]string

// WorkspaceStatus defines model for WorkspaceStatus.
type WorkspaceStatus struct {
	Conditions []schemav1.StatusCondition `json:"conditions" x-kubebuilder-validation-max-items:"32"`

	// ResourceCount Number of resources currently in the workspace
	ResourceCount *int                   `json:"resourceCount,omitempty" x-kubebuilder-validation-minimum:"0"`
	State         schemav1.ResourceState `json:"state,omitempty"`
}
