// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/resources/workspace/v1/backend/kubernetes (interfaces: WorkspacePlugin)
//
// Generated by this command:
//
//	mockgen -package kubernetes_test -destination /home/antonisio/Devel/Repos/ecp/resources/workspace/v1/backend/kubernetes/zz_mock_plugin_test.go github.com/eu-sovereign-cloud/ecp/resources/workspace/v1/backend/kubernetes WorkspacePlugin
//

// Package kubernetes_test is a generated GoMock package.
package kubernetes_test

import (
	context "context"
	reflect "reflect"

	v1 "github.com/eu-sovereign-cloud/ecp/resources/workspace/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkspacePlugin is a mock of WorkspacePlugin interface.
type MockWorkspacePlugin struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspacePluginMockRecorder
	isgomock struct{}
}

// MockWorkspacePluginMockRecorder is the mock recorder for MockWorkspacePlugin.
type MockWorkspacePluginMockRecorder struct {
	mock *MockWorkspacePlugin
}

// NewMockWorkspacePlugin creates a new mock instance.
func NewMockWorkspacePlugin(ctrl *gomock.Controller) *MockWorkspacePlugin {
	mock := &MockWorkspacePlugin{ctrl: ctrl}
	mock.recorder = &MockWorkspacePluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspacePlugin) EXPECT() *MockWorkspacePluginMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWorkspacePlugin) Create(ctx context.Context, resource *v1.Workspace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWorkspacePluginMockRecorder) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkspacePlugin)(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockWorkspacePlugin) Delete(ctx context.Context, resource *v1.Workspace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWorkspacePluginMockRecorder) Delete(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWorkspacePlugin)(nil).Delete), ctx, resource)
}
