//go:build !ignore_autogenerated

// Copyright (c) 2025 The ECP Authors
// SPDX-License-Identifier: Apache-2.0
//
// Code generated by controller-gen. DO NOT EDIT.

package kubernetes

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *InstanceSKU) DeepCopyInto(out *InstanceSKU) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

func (in *InstanceSKU) DeepCopy() *InstanceSKU {
	if in == nil {
		return nil
	}
	out := new(InstanceSKU)
	in.DeepCopyInto(out)
	return out
}

func (in *InstanceSKU) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *InstanceSKUList) DeepCopyInto(out *InstanceSKUList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InstanceSKU, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *InstanceSKUList) DeepCopy() *InstanceSKUList {
	if in == nil {
		return nil
	}
	out := new(InstanceSKUList)
	in.DeepCopyInto(out)
	return out
}

func (in *InstanceSKUList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
