// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package kubernetes

// +kubebuilder:object:generate=true
// +kubebuilder:object:root=false

// InstanceSku defines model for InstanceSku.

// Annotations User-defined key/value pairs that are mutable and can be used to add annotations.
// The number of annotations is eventually limited by the CSP.

// Extensions User-defined key/value pairs that are mutable and can be used to add extensions.
// Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.

// Labels User-defined key/value pairs that are mutable and can be used to
// organize and categorize resources. They can be used to filter resources.
// The number of labels is eventually limited by the CSP.

// Metadata Metadata for SKU resources with name, permission, type, tenant and region information.

// Spec Specification of the instance SKU, including its capabilities and extensions.

// InstanceSkuSpec Specification of the instance SKU, including its capabilities and extensions.
type InstanceSkuSpec struct {
	// Ram The amount of RAM (Random Access Memory) allocated to the instance SKU in gigabytes.
	// This value represents the total memory available to the instance.
	// +kubebuilder:validation:Maximum=65536
	// +kubebuilder:validation:Minimum=1
	Ram int `json:"ram" x-kubebuilder-validation-maximum:"65536" x-kubebuilder-validation-minimum:"1"`

	// VCPU The number of virtual CPUs (vCPUs) allocated to the instance SKU.
	// This value represents the number of cores visible to the operating system.
	// It does not specify the number of physical processors or hyper-threads available.
	// +kubebuilder:validation:Maximum=60
	// +kubebuilder:validation:Minimum=1
	VCPU int `json:"vCPU" x-kubebuilder-validation-maximum:"60" x-kubebuilder-validation-minimum:"1"`
}
