//go:build !ignore_autogenerated

// Copyright (c) 2025 The ECP Authors
// SPDX-License-Identifier: Apache-2.0
//
// Code generated by conditioned-gen. DO NOT EDIT.

package kubernetes

import (
	schemav1 "github.com/eu-sovereign-cloud/ecp/framework/persistence/kubernetes/schema/v1"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var _ schemav1.Conditioned = (*Nic)(nil)

func (x *Nic) GetConditions() []schemav1.StatusCondition {
	if x == nil || x.Status == nil {
		return nil
	}
	return x.Status.Conditions
}

func (x *Nic) PushCondition(condition schemav1.StatusCondition) {
	if x == nil {
		return
	}
	if x.Status == nil {
		x.Status = &NicStatus{}
	}
	if x.Status.Conditions == nil {
		x.Status.Conditions = []schemav1.StatusCondition{}
	}
	if condition.LastTransitionAt.IsZero() {
		condition.LastTransitionAt = metav1.Now()
	}
	prevCondition := x.PeekConditions()
	if prevCondition == nil {
		condition.Occurrences = 1
		x.Status.Conditions = append([]schemav1.StatusCondition{condition}, x.Status.Conditions...)
		x.Status.State = condition.State
		return
	}
	if schemav1.EqualConditions(*prevCondition, condition) {
		prevCondition.LastTransitionAt = condition.LastTransitionAt
		prevCondition.Occurrences++
		return
	}
	condition.Occurrences = 1
	x.Status.Conditions = append([]schemav1.StatusCondition{condition}, x.Status.Conditions...)
	x.Status.State = condition.State
}

func (x *Nic) PopCondition() {
	if x == nil || x.Status == nil || len(x.Status.Conditions) == 0 {
		return
	}
	x.Status.Conditions = x.Status.Conditions[:len(x.Status.Conditions)-1]
}

func (x *Nic) PeekConditions() *schemav1.StatusCondition {
	if x == nil || x.Status == nil || len(x.Status.Conditions) == 0 {
		return nil
	}
	return &x.Status.Conditions[0]
}

func (x *Nic) LenConditions() int {
	if x == nil || x.Status == nil {
		return 0
	}
	return len(x.Status.Conditions)
}
