// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package kubernetes

// +kubebuilder:object:generate=true
// +kubebuilder:object:root=false

import genv1 "github.com/eu-sovereign-cloud/ecp/framework/persistence/kubernetes/schema/v1"

// RouteSpec The target reference can be an instance,
// a gateway or an IP address (v4 or v6) that is part of the
// network the route table is attached to.
type RouteSpec struct {
	// DestinationCidrBlock The CIDR block for the destination. The block can be
	// a specific IP address or a range of addresses. It can be
	// IPv6 or IPv4.
	DestinationCidrBlock string `json:"destinationCidrBlock" x-cel-message-0:"spec.destinationCidrBlock must be a valid CIDR block" x-cel-rule-0:"isCIDR(self)" x-kubebuilder-validation-max-length:"43" x-kubebuilder-validation-min-length:"1"`

	// TargetRef Reference to the target of the route. The target can be an instance, an gateway or an IP address.
	TargetRef genv1.Reference `json:"targetRef"`
}

// RouteStatus defines model for RouteStatus.
type RouteStatus struct {
	Conditions []genv1.StatusCondition `json:"conditions" x-kubebuilder-validation-max-items:"32"`
	State      genv1.ResourceState     `json:"state,omitempty"`
}

// RouteTable defines model for RouteTable.

// Annotations User-defined key/value pairs that are mutable and can be used to add annotations.
// The number of annotations is eventually limited by the CSP.

// Extensions User-defined key/value pairs that are mutable and can be used to add extensions.
// Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.

// Labels User-defined key/value pairs that are mutable and can be used to
// organize and categorize resources. They can be used to filter resources.
// The number of labels is eventually limited by the CSP.

// Metadata Metadata for regional resources with name, permission, modification, type, tenant, workspace, network and region information.

// Spec The RouteTableSpec defines the routes that are associated with the route table.

// Status The status of the route table. The status is read-only and will be set by the
// system. The status contains information about the current state of the route table
// and its routes. It will report the status of the routes and the route table as a whole.

// RouteTableSpec The RouteTableSpec defines the routes that are associated with the route table.
type RouteTableSpec struct {
	Routes []RouteSpec `json:"routes" x-kubebuilder-validation-max-items:"1000" x-kubebuilder-validation-min-items:"1"`
}

// RouteTableStatus defines model for RouteTableStatus.
type RouteTableStatus struct {
	Conditions []genv1.StatusCondition `json:"conditions" x-kubebuilder-validation-max-items:"32"`
	Routes     []RouteStatus           `json:"routes,omitempty" x-kubebuilder-validation-max-items:"1000"`
	State      genv1.ResourceState     `json:"state,omitempty"`
}
