apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storage-sku-reader
rules:
  - apiGroups: ["storage.v1.secapi.cloud"]
    resources: ["storage-skus"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storage-sku-reader-binding
subjects:
  # This assumes your regional server runs under the 'default' service account
  # in the 'default' namespace. Adjust if necessary.
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: storage-sku-reader
  apiGroup: rbac.authorization.k8s.io