// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/resource/network/v1/route-table/backend/kubernetes (interfaces: RouteTablePlugin)
//
// Generated by this command:
//
//	mockgen -package kubernetes_test -destination ./zz_mock_plugin_test.go github.com/eu-sovereign-cloud/ecp/resource/network/v1/route-table/backend/kubernetes RouteTablePlugin
//

// Package kubernetes_test is a generated GoMock package.
package kubernetes_test

import (
	context "context"
	reflect "reflect"

	routetable "github.com/eu-sovereign-cloud/ecp/resource/network/v1/route-table"
	gomock "go.uber.org/mock/gomock"
)

// MockRouteTablePlugin is a mock of RouteTablePlugin interface.
type MockRouteTablePlugin struct {
	ctrl     *gomock.Controller
	recorder *MockRouteTablePluginMockRecorder
	isgomock struct{}
}

// MockRouteTablePluginMockRecorder is the mock recorder for MockRouteTablePlugin.
type MockRouteTablePluginMockRecorder struct {
	mock *MockRouteTablePlugin
}

// NewMockRouteTablePlugin creates a new mock instance.
func NewMockRouteTablePlugin(ctrl *gomock.Controller) *MockRouteTablePlugin {
	mock := &MockRouteTablePlugin{ctrl: ctrl}
	mock.recorder = &MockRouteTablePluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouteTablePlugin) EXPECT() *MockRouteTablePluginMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRouteTablePlugin) Create(ctx context.Context, resource *routetable.RouteTable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRouteTablePluginMockRecorder) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRouteTablePlugin)(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockRouteTablePlugin) Delete(ctx context.Context, resource *routetable.RouteTable) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRouteTablePluginMockRecorder) Delete(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRouteTablePlugin)(nil).Delete), ctx, resource)
}
