// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/foundation/plugin/aruba/pkg/adapter/generic/repository (interfaces: Cache,Informer)
//
// Generated by this command:
//
//	mockgen -package repository_test -destination=../../repository/zz_mock_repository_test.go github.com/eu-sovereign-cloud/ecp/foundation/plugin/aruba/pkg/adapter/generic/repository Cache,Informer
//

// Package repository_test is a generated GoMock package.
package repository_test

import (
	context "context"
	reflect "reflect"

	repository "github.com/eu-sovereign-cloud/ecp/foundation/plugin/aruba/pkg/adapter/generic/repository"
	gomock "go.uber.org/mock/gomock"
	cache "k8s.io/client-go/tools/cache"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// GetInformer mocks base method.
func (m *MockCache) GetInformer(ctx context.Context, obj client.Object) (repository.Informer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInformer", ctx, obj)
	ret0, _ := ret[0].(repository.Informer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInformer indicates an expected call of GetInformer.
func (mr *MockCacheMockRecorder) GetInformer(ctx, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInformer", reflect.TypeOf((*MockCache)(nil).GetInformer), ctx, obj)
}

// MockInformer is a mock of Informer interface.
type MockInformer struct {
	ctrl     *gomock.Controller
	recorder *MockInformerMockRecorder
	isgomock struct{}
}

// MockInformerMockRecorder is the mock recorder for MockInformer.
type MockInformerMockRecorder struct {
	mock *MockInformer
}

// NewMockInformer creates a new mock instance.
func NewMockInformer(ctrl *gomock.Controller) *MockInformer {
	mock := &MockInformer{ctrl: ctrl}
	mock.recorder = &MockInformerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInformer) EXPECT() *MockInformerMockRecorder {
	return m.recorder
}

// AddEventHandler mocks base method.
func (m *MockInformer) AddEventHandler(handler cache.ResourceEventHandler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddEventHandler", handler)
}

// AddEventHandler indicates an expected call of AddEventHandler.
func (mr *MockInformerMockRecorder) AddEventHandler(handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEventHandler", reflect.TypeOf((*MockInformer)(nil).AddEventHandler), handler)
}
