//go:build !ignore_autogenerated

// Copyright (c) 2025 The ECP Authors
// SPDX-License-Identifier: Apache-2.0
//
// Code generated by controller-gen. DO NOT EDIT.

package kubernetes

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *NetworkSKU) DeepCopyInto(out *NetworkSKU) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

func (in *NetworkSKU) DeepCopy() *NetworkSKU {
	if in == nil {
		return nil
	}
	out := new(NetworkSKU)
	in.DeepCopyInto(out)
	return out
}

func (in *NetworkSKU) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *NetworkSKUList) DeepCopyInto(out *NetworkSKUList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkSKU, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *NetworkSKUList) DeepCopy() *NetworkSKUList {
	if in == nil {
		return nil
	}
	out := new(NetworkSKUList)
	in.DeepCopyInto(out)
	return out
}

func (in *NetworkSKUList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
