// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package kubernetes

// +kubebuilder:object:generate=true
// +kubebuilder:object:root=false

// NetworkSku defines model for NetworkSku.

// Annotations User-defined key/value pairs that are mutable and can be used to add annotations.
// The number of annotations is eventually limited by the CSP.

// Extensions User-defined key/value pairs that are mutable and can be used to add extensions.
// Extensions are subject to validation by the CSP, and any value that is not accepted will be rejected during admission.

// Labels User-defined key/value pairs that are mutable and can be used to
// organize and categorize resources. They can be used to filter resources.
// The number of labels is eventually limited by the CSP.

// Metadata Metadata for SKU resources with name, permission, type, tenant and region information.

// Spec Specification of the network SKU, including its bandwidth and packets per second.

// NetworkSkuSpec Specification of the network SKU, including its bandwidth and packets per second.
type NetworkSkuSpec struct {
	// Bandwidth The bandwidth in Mbps (Megabits per second).
	// +kubebuilder:validation:Maximum=800000
	// +kubebuilder:validation:Minimum=1
	Bandwidth int `json:"bandwidth" x-kubebuilder-validation-maximum:"800000" x-kubebuilder-validation-minimum:"1"`

	// Packets The number of packets per second (PPS) that the network SKU can handle.
	// +kubebuilder:validation:Maximum=200000000000
	// +kubebuilder:validation:Minimum=1
	Packets int `json:"packets" x-kubebuilder-validation-maximum:"200000000000" x-kubebuilder-validation-minimum:"1"`
}
