// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/foundation/delegator/pkg/plugin (interfaces: Image)
//
// Generated by this command:
//
//	mockgen -package handler -destination=pkg/plugin/handler/zz_mock_image_plugin_test.go github.com/eu-sovereign-cloud/ecp/foundation/delegator/pkg/plugin Image
//

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	reflect "reflect"

	regional "github.com/eu-sovereign-cloud/ecp/foundation/models/regional"
	gomock "go.uber.org/mock/gomock"
)

// MockImage is a mock of Image interface.
type MockImage struct {
	ctrl     *gomock.Controller
	recorder *MockImageMockRecorder
	isgomock struct{}
}

// MockImageMockRecorder is the mock recorder for MockImage.
type MockImageMockRecorder struct {
	mock *MockImage
}

// NewMockImage creates a new mock instance.
func NewMockImage(ctrl *gomock.Controller) *MockImage {
	mock := &MockImage{ctrl: ctrl}
	mock.recorder = &MockImageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImage) EXPECT() *MockImageMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockImage) Create(ctx context.Context, resource *regional.ImageDomain) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockImageMockRecorder) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockImage)(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockImage) Delete(ctx context.Context, resource *regional.ImageDomain) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockImageMockRecorder) Delete(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockImage)(nil).Delete), ctx, resource)
}
