// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/foundation/delegator/pkg/plugin (interfaces: BlockStorage)
//
// Generated by this command:
//
//	mockgen -package handler -destination=zz_mock_blockstorage_plugin_test.go github.com/eu-sovereign-cloud/ecp/foundation/delegator/pkg/plugin BlockStorage
//

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	reflect "reflect"

	regional "github.com/eu-sovereign-cloud/ecp/foundation/gateway/pkg/model/regional"
	gomock "go.uber.org/mock/gomock"
)

// MockBlockStorage is a mock of BlockStorage interface.
type MockBlockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockBlockStorageMockRecorder
	isgomock struct{}
}

// MockBlockStorageMockRecorder is the mock recorder for MockBlockStorage.
type MockBlockStorageMockRecorder struct {
	mock *MockBlockStorage
}

// NewMockBlockStorage creates a new mock instance.
func NewMockBlockStorage(ctrl *gomock.Controller) *MockBlockStorage {
	mock := &MockBlockStorage{ctrl: ctrl}
	mock.recorder = &MockBlockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockStorage) EXPECT() *MockBlockStorageMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBlockStorage) Create(ctx context.Context, resource *regional.BlockStorageDomain) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBlockStorageMockRecorder) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBlockStorage)(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockBlockStorage) Delete(ctx context.Context, resource *regional.BlockStorageDomain) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBlockStorageMockRecorder) Delete(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBlockStorage)(nil).Delete), ctx, resource)
}

// IncreaseSize mocks base method.
func (m *MockBlockStorage) IncreaseSize(ctx context.Context, resource *regional.BlockStorageDomain) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseSize", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncreaseSize indicates an expected call of IncreaseSize.
func (mr *MockBlockStorageMockRecorder) IncreaseSize(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseSize", reflect.TypeOf((*MockBlockStorage)(nil).IncreaseSize), ctx, resource)
}
