// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/foundation/persistence/port (interfaces: ReaderRepo)
//
// Generated by this command:
//
//	mockgen -package=handler -destination=./pkg/adapter/handler/zz_mock_reader_repo.go github.com/eu-sovereign-cloud/ecp/foundation/persistence/port ReaderRepo
//

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	reflect "reflect"

	port "github.com/eu-sovereign-cloud/ecp/framework/kernel/port/persistence"
	"github.com/eu-sovereign-cloud/ecp/framework/kernel/resource"
	gomock "go.uber.org/mock/gomock"
)

// MockReaderRepo is a mock of ReaderRepo interface.
type MockReaderRepo[T port.IdentifiableResource] struct {
	ctrl     *gomock.Controller
	recorder *MockReaderRepoMockRecorder[T]
	isgomock struct{}
}

// MockReaderRepoMockRecorder is the mock recorder for MockReaderRepo.
type MockReaderRepoMockRecorder[T port.IdentifiableResource] struct {
	mock *MockReaderRepo[T]
}

// NewMockReaderRepo creates a new mock instance.
func NewMockReaderRepo[T port.IdentifiableResource](ctrl *gomock.Controller) *MockReaderRepo[T] {
	mock := &MockReaderRepo[T]{ctrl: ctrl}
	mock.recorder = &MockReaderRepoMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReaderRepo[T]) EXPECT() *MockReaderRepoMockRecorder[T] {
	return m.recorder
}

// List mocks base method.
func (m *MockReaderRepo[T]) List(ctx context.Context, params resource.ListParams, list *[]T) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params, list)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockReaderRepoMockRecorder[T]) List(ctx, params, list any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockReaderRepo[T])(nil).List), ctx, params, list)
}

// Load mocks base method.
func (m_2 *MockReaderRepo[T]) Load(ctx context.Context, m *T) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Load", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockReaderRepoMockRecorder[T]) Load(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockReaderRepo[T])(nil).Load), ctx, m)
}
