// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/resource/network/v1/nic/backend/kubernetes (interfaces: NicPlugin)
//
// Generated by this command:
//
//	mockgen -package kubernetes_test -destination ./zz_mock_plugin_test.go github.com/eu-sovereign-cloud/ecp/resource/network/v1/nic/backend/kubernetes NicPlugin
//

// Package kubernetes_test is a generated GoMock package.
package kubernetes_test

import (
	context "context"
	reflect "reflect"

	nic "github.com/eu-sovereign-cloud/ecp/resource/network/v1/nic"
	gomock "go.uber.org/mock/gomock"
)

// MockNicPlugin is a mock of NicPlugin interface.
type MockNicPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockNicPluginMockRecorder
	isgomock struct{}
}

// MockNicPluginMockRecorder is the mock recorder for MockNicPlugin.
type MockNicPluginMockRecorder struct {
	mock *MockNicPlugin
}

// NewMockNicPlugin creates a new mock instance.
func NewMockNicPlugin(ctrl *gomock.Controller) *MockNicPlugin {
	mock := &MockNicPlugin{ctrl: ctrl}
	mock.recorder = &MockNicPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNicPlugin) EXPECT() *MockNicPluginMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNicPlugin) Create(ctx context.Context, resource *nic.Nic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNicPluginMockRecorder) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNicPlugin)(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockNicPlugin) Delete(ctx context.Context, resource *nic.Nic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNicPluginMockRecorder) Delete(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNicPlugin)(nil).Delete), ctx, resource)
}
