//go:build !ignore_autogenerated

// Copyright (c) 2025 The ECP Authors
// SPDX-License-Identifier: Apache-2.0
//
// This file is part of the ECP project and may be used under the terms of the
// Apache License, Version 2.0. You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

// Code generated by conditioned-gen. DO NOT EDIT.

package kubernetes

import (
	schemav1 "github.com/eu-sovereign-cloud/ecp/framework/persistence/kubernetes/schema/v1"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Compile-time assertion that *Role satisfies schemav1.Conditioned.
var _ schemav1.Conditioned = (*Role)(nil)

// GetConditions returns the Status.Conditions slice, or nil
// if the receiver, its Status or the slice is nil.
func (x *Role) GetConditions() []schemav1.StatusCondition {
	if x == nil || x.Status == nil {
		return nil
	}

	return x.Status.Conditions
}

// PushCondition appends condition to Status.Conditions and mirrors its
// State onto Status.State, allocating Status or Conditions if needed.
// If condition equals the most recent entry, only its LastTransitionAt
// is updated; no new entry is appended.
func (x *Role) PushCondition(condition schemav1.StatusCondition) {
	if x == nil {
		return
	}

	if x.Status == nil {
		x.Status = &schemav1.Status{}
	}

	if x.Status.Conditions == nil {
		x.Status.Conditions = []schemav1.StatusCondition{}
	}

	if condition.LastTransitionAt.IsZero() {
		condition.LastTransitionAt = metav1.Now()
	}

	prevCondition := x.PeekConditions()
	if prevCondition == nil {
		// ensure that the condition.Occurrences field is initialized to 1 if the condition has not occurred previously
		condition.Occurrences = 1
		x.Status.Conditions = append([]schemav1.StatusCondition{condition}, x.Status.Conditions...)
		x.Status.State = condition.State
		return
	}

	if schemav1.EqualConditions(*prevCondition, condition) {
		prevCondition.LastTransitionAt = condition.LastTransitionAt
		prevCondition.Occurrences++
		return
	}

	// ensure that the condition.Occurrences field is initialized to 1 if the condition has not occurred previously
	condition.Occurrences = 1
	x.Status.Conditions = append([]schemav1.StatusCondition{condition}, x.Status.Conditions...)
	x.Status.State = condition.State
}

// PopCondition removes the oldest (tail) entry from Status.Conditions.
// It is a no-op when the slice is empty or the receiver has no status.
func (x *Role) PopCondition() {
	if x == nil || x.Status == nil || len(x.Status.Conditions) == 0 {
		return
	}

	x.Status.Conditions = x.Status.Conditions[:len(x.Status.Conditions)-1]
}

// PeekConditions returns a pointer to the most recent (head) entry in the Status.Conditions.
// If there is no Status or no Conditions in the Status, the function will always
// return nil.
func (x *Role) PeekConditions() *schemav1.StatusCondition {
	if x == nil || x.Status == nil || len(x.Status.Conditions) == 0 {
		return nil
	}

	return &x.Status.Conditions[0]
}

// LenConditions returns the length of Status.Conditions slice,
// or zero if the receiver, its Status, or the slice itself is nil.
func (x *Role) LenConditions() int {
	if x == nil || x.Status == nil {
		return 0
	}

	return len(x.Status.Conditions)
}
