//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Annotations) DeepCopyInto(out *Annotations) {
	{
		in := &in
		*out = make(Annotations, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Annotations.
func (in Annotations) DeepCopy() Annotations {
	if in == nil {
		return nil
	}
	out := new(Annotations)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cidr) DeepCopyInto(out *Cidr) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cidr.
func (in *Cidr) DeepCopy() *Cidr {
	if in == nil {
		return nil
	}
	out := new(Cidr)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonData) DeepCopyInto(out *CommonData) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(Annotations, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonData.
func (in *CommonData) DeepCopy() *CommonData {
	if in == nil {
		return nil
	}
	out := new(CommonData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Extensions) DeepCopyInto(out *Extensions) {
	{
		in := &in
		*out = make(Extensions, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Extensions.
func (in Extensions) DeepCopy() Extensions {
	if in == nil {
		return nil
	}
	out := new(Extensions)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalResourceMetadata) DeepCopyInto(out *GlobalResourceMetadata) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
	if in.DeletedAt != nil {
		in, out := &in.DeletedAt, &out.DeletedAt
		*out = (*in).DeepCopy()
	}
	in.LastModifiedAt.DeepCopyInto(&out.LastModifiedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalResourceMetadata.
func (in *GlobalResourceMetadata) DeepCopy() *GlobalResourceMetadata {
	if in == nil {
		return nil
	}
	out := new(GlobalResourceMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalTenantResourceMetadata) DeepCopyInto(out *GlobalTenantResourceMetadata) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
	if in.DeletedAt != nil {
		in, out := &in.DeletedAt, &out.DeletedAt
		*out = (*in).DeepCopy()
	}
	in.LastModifiedAt.DeepCopyInto(&out.LastModifiedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalTenantResourceMetadata.
func (in *GlobalTenantResourceMetadata) DeepCopy() *GlobalTenantResourceMetadata {
	if in == nil {
		return nil
	}
	out := new(GlobalTenantResourceMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Labels) DeepCopyInto(out *Labels) {
	{
		in := &in
		*out = make(Labels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Labels.
func (in Labels) DeepCopy() Labels {
	if in == nil {
		return nil
	}
	out := new(Labels)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModificationMetadata) DeepCopyInto(out *ModificationMetadata) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
	if in.DeletedAt != nil {
		in, out := &in.DeletedAt, &out.DeletedAt
		*out = (*in).DeepCopy()
	}
	in.LastModifiedAt.DeepCopyInto(&out.LastModifiedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModificationMetadata.
func (in *ModificationMetadata) DeepCopy() *ModificationMetadata {
	if in == nil {
		return nil
	}
	out := new(ModificationMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NameMetadata) DeepCopyInto(out *NameMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NameMetadata.
func (in *NameMetadata) DeepCopy() *NameMetadata {
	if in == nil {
		return nil
	}
	out := new(NameMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkMetadata) DeepCopyInto(out *NetworkMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkMetadata.
func (in *NetworkMetadata) DeepCopy() *NetworkMetadata {
	if in == nil {
		return nil
	}
	out := new(NetworkMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermissionMetadata) DeepCopyInto(out *PermissionMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermissionMetadata.
func (in *PermissionMetadata) DeepCopy() *PermissionMetadata {
	if in == nil {
		return nil
	}
	out := new(PermissionMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Reference) DeepCopyInto(out *Reference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reference.
func (in *Reference) DeepCopy() *Reference {
	if in == nil {
		return nil
	}
	out := new(Reference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionalMetadata) DeepCopyInto(out *RegionalMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionalMetadata.
func (in *RegionalMetadata) DeepCopy() *RegionalMetadata {
	if in == nil {
		return nil
	}
	out := new(RegionalMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionalNetworkResourceMetadata) DeepCopyInto(out *RegionalNetworkResourceMetadata) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
	if in.DeletedAt != nil {
		in, out := &in.DeletedAt, &out.DeletedAt
		*out = (*in).DeepCopy()
	}
	in.LastModifiedAt.DeepCopyInto(&out.LastModifiedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionalNetworkResourceMetadata.
func (in *RegionalNetworkResourceMetadata) DeepCopy() *RegionalNetworkResourceMetadata {
	if in == nil {
		return nil
	}
	out := new(RegionalNetworkResourceMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionalResourceMetadata) DeepCopyInto(out *RegionalResourceMetadata) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
	if in.DeletedAt != nil {
		in, out := &in.DeletedAt, &out.DeletedAt
		*out = (*in).DeepCopy()
	}
	in.LastModifiedAt.DeepCopyInto(&out.LastModifiedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionalResourceMetadata.
func (in *RegionalResourceMetadata) DeepCopy() *RegionalResourceMetadata {
	if in == nil {
		return nil
	}
	out := new(RegionalResourceMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionalWorkspaceResourceMetadata) DeepCopyInto(out *RegionalWorkspaceResourceMetadata) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
	if in.DeletedAt != nil {
		in, out := &in.DeletedAt, &out.DeletedAt
		*out = (*in).DeepCopy()
	}
	in.LastModifiedAt.DeepCopyInto(&out.LastModifiedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionalWorkspaceResourceMetadata.
func (in *RegionalWorkspaceResourceMetadata) DeepCopy() *RegionalWorkspaceResourceMetadata {
	if in == nil {
		return nil
	}
	out := new(RegionalWorkspaceResourceMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceMetadata) DeepCopyInto(out *ResourceMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceMetadata.
func (in *ResourceMetadata) DeepCopy() *ResourceMetadata {
	if in == nil {
		return nil
	}
	out := new(ResourceMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResponseMetadata) DeepCopyInto(out *ResponseMetadata) {
	*out = *in
	if in.SkipToken != nil {
		in, out := &in.SkipToken, &out.SkipToken
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResponseMetadata.
func (in *ResponseMetadata) DeepCopy() *ResponseMetadata {
	if in == nil {
		return nil
	}
	out := new(ResponseMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkuResourceMetadata) DeepCopyInto(out *SkuResourceMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkuResourceMetadata.
func (in *SkuResourceMetadata) DeepCopy() *SkuResourceMetadata {
	if in == nil {
		return nil
	}
	out := new(SkuResourceMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Status) DeepCopyInto(out *Status) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]StatusCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Status.
func (in *Status) DeepCopy() *Status {
	if in == nil {
		return nil
	}
	out := new(Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusCondition) DeepCopyInto(out *StatusCondition) {
	*out = *in
	in.LastTransitionAt.DeepCopyInto(&out.LastTransitionAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusCondition.
func (in *StatusCondition) DeepCopy() *StatusCondition {
	if in == nil {
		return nil
	}
	out := new(StatusCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemResourceMetadata) DeepCopyInto(out *SystemResourceMetadata) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(Annotations, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make(Extensions, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(Labels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemResourceMetadata.
func (in *SystemResourceMetadata) DeepCopy() *SystemResourceMetadata {
	if in == nil {
		return nil
	}
	out := new(SystemResourceMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantMetadata) DeepCopyInto(out *TenantMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantMetadata.
func (in *TenantMetadata) DeepCopy() *TenantMetadata {
	if in == nil {
		return nil
	}
	out := new(TenantMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeMetadata) DeepCopyInto(out *TypeMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeMetadata.
func (in *TypeMetadata) DeepCopy() *TypeMetadata {
	if in == nil {
		return nil
	}
	out := new(TypeMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserResourceMetadata) DeepCopyInto(out *UserResourceMetadata) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(Annotations, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make(Extensions, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(Labels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserResourceMetadata.
func (in *UserResourceMetadata) DeepCopy() *UserResourceMetadata {
	if in == nil {
		return nil
	}
	out := new(UserResourceMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeReference) DeepCopyInto(out *VolumeReference) {
	*out = *in
	out.DeviceRef = in.DeviceRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeReference.
func (in *VolumeReference) DeepCopy() *VolumeReference {
	if in == nil {
		return nil
	}
	out := new(VolumeReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceMetadata) DeepCopyInto(out *WorkspaceMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceMetadata.
func (in *WorkspaceMetadata) DeepCopy() *WorkspaceMetadata {
	if in == nil {
		return nil
	}
	out := new(WorkspaceMetadata)
	in.DeepCopyInto(out)
	return out
}

