// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/foundation/plugin/aruba/pkg/port/mutator (interfaces: Mutator)
//
// Generated by this command:
//
//	mockgen -package delegated -destination=zz_mock_mutator_test.go github.com/eu-sovereign-cloud/ecp/foundation/plugin/aruba/pkg/port/mutator Mutator
//

// Package delegated is a generated GoMock package.
package delegated

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMutator is a mock of Mutator interface.
type MockMutator[Mutable any, Params any] struct {
	ctrl     *gomock.Controller
	recorder *MockMutatorMockRecorder[Mutable, Params]
	isgomock struct{}
}

// MockMutatorMockRecorder is the mock recorder for MockMutator.
type MockMutatorMockRecorder[Mutable any, Params any] struct {
	mock *MockMutator[Mutable, Params]
}

// NewMockMutator creates a new mock instance.
func NewMockMutator[Mutable any, Params any](ctrl *gomock.Controller) *MockMutator[Mutable, Params] {
	mock := &MockMutator[Mutable, Params]{ctrl: ctrl}
	mock.recorder = &MockMutatorMockRecorder[Mutable, Params]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMutator[Mutable, Params]) EXPECT() *MockMutatorMockRecorder[Mutable, Params] {
	return m.recorder
}

// Mutate mocks base method.
func (m *MockMutator[Mutable, Params]) Mutate(mutable Mutable, params Params) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mutate", mutable, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Mutate indicates an expected call of Mutate.
func (mr *MockMutatorMockRecorder[Mutable, Params]) Mutate(mutable, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mutate", reflect.TypeOf((*MockMutator[Mutable, Params])(nil).Mutate), mutable, params)
}
