// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/foundation/plugin/aruba/pkg/port/converter (interfaces: Converter)
//
// Generated by this command:
//
//	mockgen -package delegated -destination=zz_mock_converter_test.go github.com/eu-sovereign-cloud/ecp/foundation/plugin/aruba/pkg/port/converter Converter
//

// Package delegated is a generated GoMock package.
package delegated

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockConverter is a mock of Converter interface.
type MockConverter[S any, A any] struct {
	ctrl     *gomock.Controller
	recorder *MockConverterMockRecorder[S, A]
	isgomock struct{}
}

// MockConverterMockRecorder is the mock recorder for MockConverter.
type MockConverterMockRecorder[S any, A any] struct {
	mock *MockConverter[S, A]
}

// NewMockConverter creates a new mock instance.
func NewMockConverter[S any, A any](ctrl *gomock.Controller) *MockConverter[S, A] {
	mock := &MockConverter[S, A]{ctrl: ctrl}
	mock.recorder = &MockConverterMockRecorder[S, A]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConverter[S, A]) EXPECT() *MockConverterMockRecorder[S, A] {
	return m.recorder
}

// FromArubaToSECA mocks base method.
func (m *MockConverter[S, A]) FromArubaToSECA(from A) (S, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FromArubaToSECA", from)
	ret0, _ := ret[0].(S)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FromArubaToSECA indicates an expected call of FromArubaToSECA.
func (mr *MockConverterMockRecorder[S, A]) FromArubaToSECA(from any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FromArubaToSECA", reflect.TypeOf((*MockConverter[S, A])(nil).FromArubaToSECA), from)
}

// FromSECAToAruba mocks base method.
func (m *MockConverter[S, A]) FromSECAToAruba(from S) (A, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FromSECAToAruba", from)
	ret0, _ := ret[0].(A)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FromSECAToAruba indicates an expected call of FromSECAToAruba.
func (mr *MockConverterMockRecorder[S, A]) FromSECAToAruba(from any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FromSECAToAruba", reflect.TypeOf((*MockConverter[S, A])(nil).FromSECAToAruba), from)
}
