// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/foundation/plugin/aruba/pkg/port/resolver (interfaces: DependenciesResolver)
//
// Generated by this command:
//
//	mockgen -package delegated -destination=zz_mock_resolver_test.go github.com/eu-sovereign-cloud/ecp/foundation/plugin/aruba/pkg/port/resolver DependenciesResolver
//

// Package delegated is a generated GoMock package.
package delegated

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDependenciesResolver is a mock of DependenciesResolver interface.
type MockDependenciesResolver[Main any, Bundle any] struct {
	ctrl     *gomock.Controller
	recorder *MockDependenciesResolverMockRecorder[Main, Bundle]
	isgomock struct{}
}

// MockDependenciesResolverMockRecorder is the mock recorder for MockDependenciesResolver.
type MockDependenciesResolverMockRecorder[Main any, Bundle any] struct {
	mock *MockDependenciesResolver[Main, Bundle]
}

// NewMockDependenciesResolver creates a new mock instance.
func NewMockDependenciesResolver[Main any, Bundle any](ctrl *gomock.Controller) *MockDependenciesResolver[Main, Bundle] {
	mock := &MockDependenciesResolver[Main, Bundle]{ctrl: ctrl}
	mock.recorder = &MockDependenciesResolverMockRecorder[Main, Bundle]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDependenciesResolver[Main, Bundle]) EXPECT() *MockDependenciesResolverMockRecorder[Main, Bundle] {
	return m.recorder
}

// ResolveDependencies mocks base method.
func (m *MockDependenciesResolver[Main, Bundle]) ResolveDependencies(ctx context.Context, main Main) (Bundle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveDependencies", ctx, main)
	ret0, _ := ret[0].(Bundle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveDependencies indicates an expected call of ResolveDependencies.
func (mr *MockDependenciesResolverMockRecorder[Main, Bundle]) ResolveDependencies(ctx, main any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveDependencies", reflect.TypeOf((*MockDependenciesResolver[Main, Bundle])(nil).ResolveDependencies), ctx, main)
}
