// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/foundation/gateway/pkg/port (interfaces: IdentifiableResource)
//
// Generated by this command:
//
//	mockgen -package delegated -destination=zz_mock_identifiable_test.go github.com/eu-sovereign-cloud/ecp/foundation/gateway/pkg/port IdentifiableResource
//

// Package delegated is a generated GoMock package.
package delegated

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIdentifiableResource is a mock of IdentifiableResource interface.
type MockIdentifiableResource struct {
	ctrl     *gomock.Controller
	recorder *MockIdentifiableResourceMockRecorder
	isgomock struct{}
}

// MockIdentifiableResourceMockRecorder is the mock recorder for MockIdentifiableResource.
type MockIdentifiableResourceMockRecorder struct {
	mock *MockIdentifiableResource
}

// NewMockIdentifiableResource creates a new mock instance.
func NewMockIdentifiableResource(ctrl *gomock.Controller) *MockIdentifiableResource {
	mock := &MockIdentifiableResource{ctrl: ctrl}
	mock.recorder = &MockIdentifiableResourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentifiableResource) EXPECT() *MockIdentifiableResourceMockRecorder {
	return m.recorder
}

// GetName mocks base method.
func (m *MockIdentifiableResource) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockIdentifiableResourceMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockIdentifiableResource)(nil).GetName))
}

// GetTenant mocks base method.
func (m *MockIdentifiableResource) GetTenant() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenant")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTenant indicates an expected call of GetTenant.
func (mr *MockIdentifiableResourceMockRecorder) GetTenant() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenant", reflect.TypeOf((*MockIdentifiableResource)(nil).GetTenant))
}

// GetVersion mocks base method.
func (m *MockIdentifiableResource) GetVersion() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockIdentifiableResourceMockRecorder) GetVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockIdentifiableResource)(nil).GetVersion))
}

// GetWorkspace mocks base method.
func (m *MockIdentifiableResource) GetWorkspace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetWorkspace indicates an expected call of GetWorkspace.
func (mr *MockIdentifiableResourceMockRecorder) GetWorkspace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspace", reflect.TypeOf((*MockIdentifiableResource)(nil).GetWorkspace))
}
