// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/foundation/plugin/aruba/pkg/port/repository (interfaces: Writer,Watcher)
//
// Generated by this command:
//
//	mockgen -package delegated -destination=zz_mock_repository_test.go github.com/eu-sovereign-cloud/ecp/foundation/plugin/aruba/pkg/port/repository Writer,Watcher
//

// Package delegated is a generated GoMock package.
package delegated

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWriter is a mock of Writer interface.
type MockWriter[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder[T]
	isgomock struct{}
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder[T any] struct {
	mock *MockWriter[T]
}

// NewMockWriter creates a new mock instance.
func NewMockWriter[T any](ctrl *gomock.Controller) *MockWriter[T] {
	mock := &MockWriter[T]{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter[T]) EXPECT() *MockWriterMockRecorder[T] {
	return m.recorder
}

// Create mocks base method.
func (m *MockWriter[T]) Create(ctx context.Context, resource T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWriterMockRecorder[T]) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWriter[T])(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockWriter[T]) Delete(ctx context.Context, resource T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWriterMockRecorder[T]) Delete(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWriter[T])(nil).Delete), ctx, resource)
}

// Update mocks base method.
func (m *MockWriter[T]) Update(ctx context.Context, resource T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWriterMockRecorder[T]) Update(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWriter[T])(nil).Update), ctx, resource)
}

// MockWatcher is a mock of Watcher interface.
type MockWatcher[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockWatcherMockRecorder[T]
	isgomock struct{}
}

// MockWatcherMockRecorder is the mock recorder for MockWatcher.
type MockWatcherMockRecorder[T any] struct {
	mock *MockWatcher[T]
}

// NewMockWatcher creates a new mock instance.
func NewMockWatcher[T any](ctrl *gomock.Controller) *MockWatcher[T] {
	mock := &MockWatcher[T]{ctrl: ctrl}
	mock.recorder = &MockWatcherMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatcher[T]) EXPECT() *MockWatcherMockRecorder[T] {
	return m.recorder
}

// Watch mocks base method.
func (m *MockWatcher[T]) Watch(ctx context.Context, resource T) (chan T, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", ctx, resource)
	ret0, _ := ret[0].(chan T)
	ret1, _ := ret[1].(func())
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Watch indicates an expected call of Watch.
func (mr *MockWatcherMockRecorder[T]) Watch(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockWatcher[T])(nil).Watch), ctx, resource)
}
