// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eu-sovereign-cloud/ecp/resource/storage/image/v1/backend/kubernetes (interfaces: ImagePlugin)
//
// Generated by this command:
//
//	mockgen -package kubernetes_test -destination ./zz_mock_plugin_test.go github.com/eu-sovereign-cloud/ecp/resource/storage/image/v1/backend/kubernetes ImagePlugin
//

// Package kubernetes_test is a generated GoMock package.
package kubernetes_test

import (
	context "context"
	reflect "reflect"

	v1 "github.com/eu-sovereign-cloud/ecp/resource/storage/image/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockImagePlugin is a mock of ImagePlugin interface.
type MockImagePlugin struct {
	ctrl     *gomock.Controller
	recorder *MockImagePluginMockRecorder
	isgomock struct{}
}

// MockImagePluginMockRecorder is the mock recorder for MockImagePlugin.
type MockImagePluginMockRecorder struct {
	mock *MockImagePlugin
}

// NewMockImagePlugin creates a new mock instance.
func NewMockImagePlugin(ctrl *gomock.Controller) *MockImagePlugin {
	mock := &MockImagePlugin{ctrl: ctrl}
	mock.recorder = &MockImagePluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImagePlugin) EXPECT() *MockImagePluginMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockImagePlugin) Create(ctx context.Context, resource *v1.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockImagePluginMockRecorder) Create(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockImagePlugin)(nil).Create), ctx, resource)
}

// Delete mocks base method.
func (m *MockImagePlugin) Delete(ctx context.Context, resource *v1.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockImagePluginMockRecorder) Delete(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockImagePlugin)(nil).Delete), ctx, resource)
}
