//go:build !ignore_autogenerated

// Copyright (c) 2025 The ECP Authors
// SPDX-License-Identifier: Apache-2.0
//
// Code generated by controller-gen. DO NOT EDIT.

package kubernetes

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *StorageSKU) DeepCopyInto(out *StorageSKU) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

func (in *StorageSKU) DeepCopy() *StorageSKU {
	if in == nil {
		return nil
	}
	out := new(StorageSKU)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageSKU) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *StorageSKUList) DeepCopyInto(out *StorageSKUList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageSKU, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *StorageSKUList) DeepCopy() *StorageSKUList {
	if in == nil {
		return nil
	}
	out := new(StorageSKUList)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageSKUList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
