name: SonarQube

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.yaml"
      - "**/*.json"
  pull_request:

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
